/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIError } from '../models';
// @ts-ignore
import type { ShowBarcodeResponse } from '../models';
/**
 * BarcodesApi - axios parameter creator
 */
export const BarcodesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Fetches the latest barcode for a konbini payment.  Barcodes can be displayed in your client application to give your customers a more convenient way to pay. Not all konbini payments are compatible with barcodes. If a payment is compatible, it will have a `barcode_url` field in its `payment_details` object, which is a reference to this endpoint.  Newly created payments may not have a barcode available immediately. If the barcode is still being generated, the response will have a `status` of `pending` and a `retry_after` field indicating how many seconds to wait before you may retry the request.  The barcodes can only be used for payment for a limited amount of time, by default this is 10 minutes. Subsequent requests to this endpoint will return the same barcode as long as it is still valid. After expiration, a new barcode will be generated and returned.  <details> <summary>Fetching barcodes in JavaScript</summary>  If you\'re integrating barcodes on your website, the following JavaScript function can be used to fetch barcode data, handling the pending status and retrying. The `barcode_url` parameter is returned from Payments APIs when the payment is compatible with barcodes.  ```javascript async function fetchBarcode(barcode_url) {   const response = await fetch(barcode_url);   if (!response.ok) {     throw new Error(       `Error fetching barcode: ${response.status} ${response.statusText}`     );   }    const { status, retry_after, ...barcode } = await response.json();   if (status === \'ready\') {     return barcode;   } else if (status === \'pending\') {     await new Promise(resolve => setTimeout(resolve, retry_after * 1000));     return fetchBarcode(barcode_url);   } else {     throw new Error(`Error fetching barcode: unexpected status ${status}`);   } } ``` </details>
         * @summary Barcode: Show
         * @param {string} paymentId Payment unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showBarcode: async (paymentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paymentId' is not null or undefined
            assertParamExists('showBarcode', 'paymentId', paymentId)
            const localVarPath = `/barcodes/{payment_id}`
                .replace('{payment_id}', encodeURIComponent(String(paymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BarcodesApi - functional programming interface
 */
export const BarcodesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BarcodesApiAxiosParamCreator(configuration)
    return {
        /**
         * Fetches the latest barcode for a konbini payment.  Barcodes can be displayed in your client application to give your customers a more convenient way to pay. Not all konbini payments are compatible with barcodes. If a payment is compatible, it will have a `barcode_url` field in its `payment_details` object, which is a reference to this endpoint.  Newly created payments may not have a barcode available immediately. If the barcode is still being generated, the response will have a `status` of `pending` and a `retry_after` field indicating how many seconds to wait before you may retry the request.  The barcodes can only be used for payment for a limited amount of time, by default this is 10 minutes. Subsequent requests to this endpoint will return the same barcode as long as it is still valid. After expiration, a new barcode will be generated and returned.  <details> <summary>Fetching barcodes in JavaScript</summary>  If you\'re integrating barcodes on your website, the following JavaScript function can be used to fetch barcode data, handling the pending status and retrying. The `barcode_url` parameter is returned from Payments APIs when the payment is compatible with barcodes.  ```javascript async function fetchBarcode(barcode_url) {   const response = await fetch(barcode_url);   if (!response.ok) {     throw new Error(       `Error fetching barcode: ${response.status} ${response.statusText}`     );   }    const { status, retry_after, ...barcode } = await response.json();   if (status === \'ready\') {     return barcode;   } else if (status === \'pending\') {     await new Promise(resolve => setTimeout(resolve, retry_after * 1000));     return fetchBarcode(barcode_url);   } else {     throw new Error(`Error fetching barcode: unexpected status ${status}`);   } } ``` </details>
         * @summary Barcode: Show
         * @param {string} paymentId Payment unique identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showBarcode(paymentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ShowBarcodeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showBarcode(paymentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BarcodesApi.showBarcode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BarcodesApi - factory interface
 */
export const BarcodesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BarcodesApiFp(configuration)
    return {
        /**
         * Fetches the latest barcode for a konbini payment.  Barcodes can be displayed in your client application to give your customers a more convenient way to pay. Not all konbini payments are compatible with barcodes. If a payment is compatible, it will have a `barcode_url` field in its `payment_details` object, which is a reference to this endpoint.  Newly created payments may not have a barcode available immediately. If the barcode is still being generated, the response will have a `status` of `pending` and a `retry_after` field indicating how many seconds to wait before you may retry the request.  The barcodes can only be used for payment for a limited amount of time, by default this is 10 minutes. Subsequent requests to this endpoint will return the same barcode as long as it is still valid. After expiration, a new barcode will be generated and returned.  <details> <summary>Fetching barcodes in JavaScript</summary>  If you\'re integrating barcodes on your website, the following JavaScript function can be used to fetch barcode data, handling the pending status and retrying. The `barcode_url` parameter is returned from Payments APIs when the payment is compatible with barcodes.  ```javascript async function fetchBarcode(barcode_url) {   const response = await fetch(barcode_url);   if (!response.ok) {     throw new Error(       `Error fetching barcode: ${response.status} ${response.statusText}`     );   }    const { status, retry_after, ...barcode } = await response.json();   if (status === \'ready\') {     return barcode;   } else if (status === \'pending\') {     await new Promise(resolve => setTimeout(resolve, retry_after * 1000));     return fetchBarcode(barcode_url);   } else {     throw new Error(`Error fetching barcode: unexpected status ${status}`);   } } ``` </details>
         * @summary Barcode: Show
         * @param {BarcodesApiShowBarcodeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showBarcode(requestParameters: BarcodesApiShowBarcodeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ShowBarcodeResponse> {
            return localVarFp.showBarcode(requestParameters.paymentId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for showBarcode operation in BarcodesApi.
 */
export interface BarcodesApiShowBarcodeRequest {
    /**
     * Payment unique identifier
     */
    readonly paymentId: string
}

/**
 * BarcodesApi - object-oriented interface
 */
export class BarcodesApi extends BaseAPI {
    /**
     * Fetches the latest barcode for a konbini payment.  Barcodes can be displayed in your client application to give your customers a more convenient way to pay. Not all konbini payments are compatible with barcodes. If a payment is compatible, it will have a `barcode_url` field in its `payment_details` object, which is a reference to this endpoint.  Newly created payments may not have a barcode available immediately. If the barcode is still being generated, the response will have a `status` of `pending` and a `retry_after` field indicating how many seconds to wait before you may retry the request.  The barcodes can only be used for payment for a limited amount of time, by default this is 10 minutes. Subsequent requests to this endpoint will return the same barcode as long as it is still valid. After expiration, a new barcode will be generated and returned.  <details> <summary>Fetching barcodes in JavaScript</summary>  If you\'re integrating barcodes on your website, the following JavaScript function can be used to fetch barcode data, handling the pending status and retrying. The `barcode_url` parameter is returned from Payments APIs when the payment is compatible with barcodes.  ```javascript async function fetchBarcode(barcode_url) {   const response = await fetch(barcode_url);   if (!response.ok) {     throw new Error(       `Error fetching barcode: ${response.status} ${response.statusText}`     );   }    const { status, retry_after, ...barcode } = await response.json();   if (status === \'ready\') {     return barcode;   } else if (status === \'pending\') {     await new Promise(resolve => setTimeout(resolve, retry_after * 1000));     return fetchBarcode(barcode_url);   } else {     throw new Error(`Error fetching barcode: unexpected status ${status}`);   } } ``` </details>
     * @summary Barcode: Show
     * @param {BarcodesApiShowBarcodeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public showBarcode(requestParameters: BarcodesApiShowBarcodeRequest, options?: RawAxiosRequestConfig) {
        return BarcodesApiFp(this.configuration).showBarcode(requestParameters.paymentId, options).then((request) => request(this.axios, this.basePath));
    }
}

