/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIError } from '../models';
// @ts-ignore
import type { ChargebackRequestDetail } from '../models';
// @ts-ignore
import type { ChargebackRequestList } from '../models';
// @ts-ignore
import type { ChargebackStatus } from '../models';
// @ts-ignore
import type { DefendChargebackRequestBody } from '../models';
/**
 * ChargebacksApi - axios parameter creator
 */
export const ChargebacksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Accepts a chargeback, agreeing to the dispute. Takes no request body.  A chargeback can only be accepted while its status is `pending`. If the due date has passed, the request returns an error. Accepting an already-accepted chargeback returns `204` (idempotent).
         * @summary Chargeback: Accept
         * @param {string} id The chargeback request UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        acceptChargebackRequest: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('acceptChargebackRequest', 'id', id)
            const localVarPath = `/chargeback_requests/{id}/accept`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Submits a defense against a chargeback, including supporting documentation.  A chargeback can only be defended while its status is `pending`. If the due date has passed, the request returns an error. Defending an already-defended chargeback returns `204` (idempotent). Only one defense can be created per chargeback request.  The `document.document_base64` payload must be 15 MB or less. Supported types are PDF, JPG/JPEG, PNG, and GIF; the type is inferred from the file\'s bytes, not the filename.
         * @summary Chargeback: Defend
         * @param {string} id The chargeback request UUID.
         * @param {DefendChargebackRequestBody} defendChargebackRequestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        defendChargebackRequest: async (id: string, defendChargebackRequestBody: DefendChargebackRequestBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('defendChargebackRequest', 'id', id)
            // verify required parameter 'defendChargebackRequestBody' is not null or undefined
            assertParamExists('defendChargebackRequest', 'defendChargebackRequestBody', defendChargebackRequestBody)
            const localVarPath = `/chargeback_requests/{id}/defend`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(defendChargebackRequestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a paginated list of chargeback requests for the authenticated merchant.  Results are ordered with `pending` chargebacks first, followed by non-pending chargebacks. There is no request sort parameter.  This endpoint is only available to merchants with the chargeback feature enabled; otherwise it returns `404 Not Found`.
         * @summary Chargeback: List
         * @param {string} [startTime] Query for records created after this time.
         * @param {string} [endTime] Query for records created before this time.
         * @param {number} [perPage] How many objects per page.
         * @param {number} [page] Page number to query for.
         * @param {ChargebackStatus} [status] Filter by chargeback status.
         * @param {string} [paymentId] Filter by the associated payment ID.
         * @param {string} [dueDateStart] Lower bound (inclusive) on the chargeback\&#39;s due date.
         * @param {string} [dueDateEnd] Upper bound (inclusive) on the chargeback\&#39;s due date.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChargebackRequests: async (startTime?: string, endTime?: string, perPage?: number, page?: number, status?: ChargebackStatus, paymentId?: string, dueDateStart?: string, dueDateEnd?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/chargeback_requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (startTime !== undefined) {
                localVarQueryParameter['start_time'] = (startTime as any instanceof Date) ?
                    (startTime as any).toISOString() :
                    startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['end_time'] = (endTime as any instanceof Date) ?
                    (endTime as any).toISOString() :
                    endTime;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (paymentId !== undefined) {
                localVarQueryParameter['payment_id'] = paymentId;
            }

            if (dueDateStart !== undefined) {
                localVarQueryParameter['due_date_start'] = (dueDateStart as any instanceof Date) ?
                    (dueDateStart as any).toISOString() :
                    dueDateStart;
            }

            if (dueDateEnd !== undefined) {
                localVarQueryParameter['due_date_end'] = (dueDateEnd as any instanceof Date) ?
                    (dueDateEnd as any).toISOString() :
                    dueDateEnd;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the details of a single chargeback request, including its timeline, payment, customer, and defense (if one exists).  This endpoint is only available to merchants with the chargeback feature enabled; otherwise it returns `404 Not Found`.
         * @summary Chargeback: Show
         * @param {string} id The chargeback request UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showChargebackRequest: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('showChargebackRequest', 'id', id)
            const localVarPath = `/chargeback_requests/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChargebacksApi - functional programming interface
 */
export const ChargebacksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ChargebacksApiAxiosParamCreator(configuration)
    return {
        /**
         * Accepts a chargeback, agreeing to the dispute. Takes no request body.  A chargeback can only be accepted while its status is `pending`. If the due date has passed, the request returns an error. Accepting an already-accepted chargeback returns `204` (idempotent).
         * @summary Chargeback: Accept
         * @param {string} id The chargeback request UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async acceptChargebackRequest(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.acceptChargebackRequest(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChargebacksApi.acceptChargebackRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Submits a defense against a chargeback, including supporting documentation.  A chargeback can only be defended while its status is `pending`. If the due date has passed, the request returns an error. Defending an already-defended chargeback returns `204` (idempotent). Only one defense can be created per chargeback request.  The `document.document_base64` payload must be 15 MB or less. Supported types are PDF, JPG/JPEG, PNG, and GIF; the type is inferred from the file\'s bytes, not the filename.
         * @summary Chargeback: Defend
         * @param {string} id The chargeback request UUID.
         * @param {DefendChargebackRequestBody} defendChargebackRequestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async defendChargebackRequest(id: string, defendChargebackRequestBody: DefendChargebackRequestBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.defendChargebackRequest(id, defendChargebackRequestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChargebacksApi.defendChargebackRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a paginated list of chargeback requests for the authenticated merchant.  Results are ordered with `pending` chargebacks first, followed by non-pending chargebacks. There is no request sort parameter.  This endpoint is only available to merchants with the chargeback feature enabled; otherwise it returns `404 Not Found`.
         * @summary Chargeback: List
         * @param {string} [startTime] Query for records created after this time.
         * @param {string} [endTime] Query for records created before this time.
         * @param {number} [perPage] How many objects per page.
         * @param {number} [page] Page number to query for.
         * @param {ChargebackStatus} [status] Filter by chargeback status.
         * @param {string} [paymentId] Filter by the associated payment ID.
         * @param {string} [dueDateStart] Lower bound (inclusive) on the chargeback\&#39;s due date.
         * @param {string} [dueDateEnd] Upper bound (inclusive) on the chargeback\&#39;s due date.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listChargebackRequests(startTime?: string, endTime?: string, perPage?: number, page?: number, status?: ChargebackStatus, paymentId?: string, dueDateStart?: string, dueDateEnd?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChargebackRequestList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listChargebackRequests(startTime, endTime, perPage, page, status, paymentId, dueDateStart, dueDateEnd, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChargebacksApi.listChargebackRequests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves the details of a single chargeback request, including its timeline, payment, customer, and defense (if one exists).  This endpoint is only available to merchants with the chargeback feature enabled; otherwise it returns `404 Not Found`.
         * @summary Chargeback: Show
         * @param {string} id The chargeback request UUID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showChargebackRequest(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChargebackRequestDetail>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showChargebackRequest(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChargebacksApi.showChargebackRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ChargebacksApi - factory interface
 */
export const ChargebacksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ChargebacksApiFp(configuration)
    return {
        /**
         * Accepts a chargeback, agreeing to the dispute. Takes no request body.  A chargeback can only be accepted while its status is `pending`. If the due date has passed, the request returns an error. Accepting an already-accepted chargeback returns `204` (idempotent).
         * @summary Chargeback: Accept
         * @param {ChargebacksApiAcceptChargebackRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        acceptChargebackRequest(requestParameters: ChargebacksApiAcceptChargebackRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.acceptChargebackRequest(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Submits a defense against a chargeback, including supporting documentation.  A chargeback can only be defended while its status is `pending`. If the due date has passed, the request returns an error. Defending an already-defended chargeback returns `204` (idempotent). Only one defense can be created per chargeback request.  The `document.document_base64` payload must be 15 MB or less. Supported types are PDF, JPG/JPEG, PNG, and GIF; the type is inferred from the file\'s bytes, not the filename.
         * @summary Chargeback: Defend
         * @param {ChargebacksApiDefendChargebackRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        defendChargebackRequest(requestParameters: ChargebacksApiDefendChargebackRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.defendChargebackRequest(requestParameters.id, requestParameters.defendChargebackRequestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a paginated list of chargeback requests for the authenticated merchant.  Results are ordered with `pending` chargebacks first, followed by non-pending chargebacks. There is no request sort parameter.  This endpoint is only available to merchants with the chargeback feature enabled; otherwise it returns `404 Not Found`.
         * @summary Chargeback: List
         * @param {ChargebacksApiListChargebackRequestsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listChargebackRequests(requestParameters: ChargebacksApiListChargebackRequestsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ChargebackRequestList> {
            return localVarFp.listChargebackRequests(requestParameters.startTime, requestParameters.endTime, requestParameters.perPage, requestParameters.page, requestParameters.status, requestParameters.paymentId, requestParameters.dueDateStart, requestParameters.dueDateEnd, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the details of a single chargeback request, including its timeline, payment, customer, and defense (if one exists).  This endpoint is only available to merchants with the chargeback feature enabled; otherwise it returns `404 Not Found`.
         * @summary Chargeback: Show
         * @param {ChargebacksApiShowChargebackRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showChargebackRequest(requestParameters: ChargebacksApiShowChargebackRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<ChargebackRequestDetail> {
            return localVarFp.showChargebackRequest(requestParameters.id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for acceptChargebackRequest operation in ChargebacksApi.
 */
export interface ChargebacksApiAcceptChargebackRequestRequest {
    /**
     * The chargeback request UUID.
     */
    readonly id: string
}

/**
 * Request parameters for defendChargebackRequest operation in ChargebacksApi.
 */
export interface ChargebacksApiDefendChargebackRequestRequest {
    /**
     * The chargeback request UUID.
     */
    readonly id: string

    readonly defendChargebackRequestBody: DefendChargebackRequestBody
}

/**
 * Request parameters for listChargebackRequests operation in ChargebacksApi.
 */
export interface ChargebacksApiListChargebackRequestsRequest {
    /**
     * Query for records created after this time.
     */
    readonly startTime?: string

    /**
     * Query for records created before this time.
     */
    readonly endTime?: string

    /**
     * How many objects per page.
     */
    readonly perPage?: number

    /**
     * Page number to query for.
     */
    readonly page?: number

    /**
     * Filter by chargeback status.
     */
    readonly status?: ChargebackStatus

    /**
     * Filter by the associated payment ID.
     */
    readonly paymentId?: string

    /**
     * Lower bound (inclusive) on the chargeback\&#39;s due date.
     */
    readonly dueDateStart?: string

    /**
     * Upper bound (inclusive) on the chargeback\&#39;s due date.
     */
    readonly dueDateEnd?: string
}

/**
 * Request parameters for showChargebackRequest operation in ChargebacksApi.
 */
export interface ChargebacksApiShowChargebackRequestRequest {
    /**
     * The chargeback request UUID.
     */
    readonly id: string
}

/**
 * ChargebacksApi - object-oriented interface
 */
export class ChargebacksApi extends BaseAPI {
    /**
     * Accepts a chargeback, agreeing to the dispute. Takes no request body.  A chargeback can only be accepted while its status is `pending`. If the due date has passed, the request returns an error. Accepting an already-accepted chargeback returns `204` (idempotent).
     * @summary Chargeback: Accept
     * @param {ChargebacksApiAcceptChargebackRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public acceptChargebackRequest(requestParameters: ChargebacksApiAcceptChargebackRequestRequest, options?: RawAxiosRequestConfig) {
        return ChargebacksApiFp(this.configuration).acceptChargebackRequest(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Submits a defense against a chargeback, including supporting documentation.  A chargeback can only be defended while its status is `pending`. If the due date has passed, the request returns an error. Defending an already-defended chargeback returns `204` (idempotent). Only one defense can be created per chargeback request.  The `document.document_base64` payload must be 15 MB or less. Supported types are PDF, JPG/JPEG, PNG, and GIF; the type is inferred from the file\'s bytes, not the filename.
     * @summary Chargeback: Defend
     * @param {ChargebacksApiDefendChargebackRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public defendChargebackRequest(requestParameters: ChargebacksApiDefendChargebackRequestRequest, options?: RawAxiosRequestConfig) {
        return ChargebacksApiFp(this.configuration).defendChargebackRequest(requestParameters.id, requestParameters.defendChargebackRequestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a paginated list of chargeback requests for the authenticated merchant.  Results are ordered with `pending` chargebacks first, followed by non-pending chargebacks. There is no request sort parameter.  This endpoint is only available to merchants with the chargeback feature enabled; otherwise it returns `404 Not Found`.
     * @summary Chargeback: List
     * @param {ChargebacksApiListChargebackRequestsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listChargebackRequests(requestParameters: ChargebacksApiListChargebackRequestsRequest = {}, options?: RawAxiosRequestConfig) {
        return ChargebacksApiFp(this.configuration).listChargebackRequests(requestParameters.startTime, requestParameters.endTime, requestParameters.perPage, requestParameters.page, requestParameters.status, requestParameters.paymentId, requestParameters.dueDateStart, requestParameters.dueDateEnd, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the details of a single chargeback request, including its timeline, payment, customer, and defense (if one exists).  This endpoint is only available to merchants with the chargeback feature enabled; otherwise it returns `404 Not Found`.
     * @summary Chargeback: Show
     * @param {ChargebacksApiShowChargebackRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public showChargebackRequest(requestParameters: ChargebacksApiShowChargebackRequestRequest, options?: RawAxiosRequestConfig) {
        return ChargebacksApiFp(this.configuration).showChargebackRequest(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
}

