/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIError } from '../models';
// @ts-ignore
import type { AvailablePaymentMethod } from '../models';
// @ts-ignore
import type { CapturePaymentRequest } from '../models';
// @ts-ignore
import type { CreatePaymentRequest } from '../models';
// @ts-ignore
import type { CreateRefundRequestRequest } from '../models';
// @ts-ignore
import type { Currency } from '../models';
// @ts-ignore
import type { FinalizePaymentRequest } from '../models';
// @ts-ignore
import type { Payment } from '../models';
// @ts-ignore
import type { PaymentList } from '../models';
// @ts-ignore
import type { RefundPaymentRequest } from '../models';
// @ts-ignore
import type { TerminalError } from '../models';
// @ts-ignore
import type { UpdatePaymentRequest } from '../models';
/**
 * PaymentsApi - axios parameter creator
 * @export
 */
export const PaymentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Cancels a payment.  The given payment must have a state of `pending` or `authorized` in order to be canceled.
         * @summary Payment: Cancel
         * @param {string} id A unique identifier for the payment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelPayment: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cancelPayment', 'id', id)
            const localVarPath = `/payments/{id}/cancel`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Captures a payment.  Only works when the payment was created with `capture` set to false, or via a session with `capture` set to `\"manual\"`.
         * @summary Payment: Capture
         * @param {string} id A unique identifier for the payment.
         * @param {CapturePaymentRequest} capturePaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        capturePayment: async (id: string, capturePaymentRequest: CapturePaymentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('capturePayment', 'id', id)
            // verify required parameter 'capturePaymentRequest' is not null or undefined
            assertParamExists('capturePayment', 'capturePaymentRequest', capturePaymentRequest)
            const localVarPath = `/payments/{id}/capture`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(capturePaymentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a payment for a given `amount` and `currency`.  There are two ways to create payment:  - For one-time payment, you can pass `payment_details` with payment method type and additional attributes. - For recurring payment, you can pass customer\'s ID via `customer` attribute. Customer\'s saved payment method will be used for the payment.  Note that either `payment_details` or `customer` is required for the payment. However, both of them should not be given at the same time.
         * @summary Payment: Create
         * @param {CreatePaymentRequest} createPaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPayment: async (createPaymentRequest: CreatePaymentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createPaymentRequest' is not null or undefined
            assertParamExists('createPayment', 'createPaymentRequest', createPaymentRequest)
            const localVarPath = `/payments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createPaymentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * A \"Refund Request\" requests that a payment be refunded manually. This can be used for payment methods that do not support refunds, such as konbini. To support non-refundable payment methods, a bank account must be specified so that we know where to send the funds. Since it is a manual process, the refund will be carried out at a later date, and there\'s a possibility of it being rejected.
         * @summary Payment: Refund Request
         * @param {string} id A unique identifier for the payment.
         * @param {CreateRefundRequestRequest} createRefundRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRefundRequest: async (id: string, createRefundRequestRequest: CreateRefundRequestRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('createRefundRequest', 'id', id)
            // verify required parameter 'createRefundRequestRequest' is not null or undefined
            assertParamExists('createRefundRequest', 'createRefundRequestRequest', createRefundRequestRequest)
            const localVarPath = `/payments/{id}/refund_request`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createRefundRequestRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Finalizes a payment.  Finalizes an EMV contact transaction by confirming the chip card\'s final decision (TC for approved, AAC for declined). Use this after authorization to submit the terminal\'s transaction outcome and determine whether the payment is captured or cancelled.
         * @summary Payment: Finalize
         * @param {string} id A unique identifier for the payment.
         * @param {FinalizePaymentRequest} finalizePaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finalizePayment: async (id: string, finalizePaymentRequest: FinalizePaymentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('finalizePayment', 'id', id)
            // verify required parameter 'finalizePaymentRequest' is not null or undefined
            assertParamExists('finalizePayment', 'finalizePaymentRequest', finalizePaymentRequest)
            const localVarPath = `/payments/{id}/finalize`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(finalizePaymentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lists available payment methods.
         * @summary Payment Method: List
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPaymentMethods: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/payment_methods`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a paginated list of payments. Pagination can be configured with `page` and `per_page` parameters.  Payments can be filtered by `currency`, `external_order_num`, and `status`.  A time range can be specified with `start_time`, and `end_time`.
         * @summary Payment: List
         * @param {string} [startTime] Query for records created after this time.
         * @param {string} [endTime] Query for records created before this time.
         * @param {number} [perPage] How many objects per page.
         * @param {number} [page] Page number to query for.
         * @param {string} [merchantId] 
         * @param {Currency} [currency] 
         * @param {string} [externalOrderNum] A unique ID from your application used to track this payment.
         * @param {string} [status] The status of the payment. Can be a single status or comma-separated values.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPayments: async (startTime?: string, endTime?: string, perPage?: number, page?: number, merchantId?: string, currency?: Currency, externalOrderNum?: string, status?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/payments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (startTime !== undefined) {
                localVarQueryParameter['start_time'] = (startTime as any instanceof Date) ?
                    (startTime as any).toISOString() :
                    startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['end_time'] = (endTime as any instanceof Date) ?
                    (endTime as any).toISOString() :
                    endTime;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (merchantId !== undefined) {
                localVarQueryParameter['merchant_id'] = merchantId;
            }

            if (currency !== undefined) {
                localVarQueryParameter['currency'] = currency;
            }

            if (externalOrderNum !== undefined) {
                localVarQueryParameter['external_order_num'] = externalOrderNum;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Refunds an arbitrary amount of money from an existing payment. If no amount is specified, the whole payment is refunded.
         * @summary Payment: Refund
         * @param {string} id A unique identifier for the payment.
         * @param {RefundPaymentRequest} refundPaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refundPayment: async (id: string, refundPaymentRequest: RefundPaymentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('refundPayment', 'id', id)
            // verify required parameter 'refundPaymentRequest' is not null or undefined
            assertParamExists('refundPayment', 'refundPaymentRequest', refundPaymentRequest)
            const localVarPath = `/payments/{id}/refund`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(refundPaymentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a single payment object by its `id`.
         * @summary Payment: Show
         * @param {string} id A unique identifier for the payment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showPayment: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('showPayment', 'id', id)
            const localVarPath = `/payments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates a payment.  Only a payment\'s `description` and `metadata` can be changed.
         * @summary Payment: Update
         * @param {string} id A unique identifier for the payment.
         * @param {UpdatePaymentRequest} updatePaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePayment: async (id: string, updatePaymentRequest: UpdatePaymentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updatePayment', 'id', id)
            // verify required parameter 'updatePaymentRequest' is not null or undefined
            assertParamExists('updatePayment', 'updatePaymentRequest', updatePaymentRequest)
            const localVarPath = `/payments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updatePaymentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentsApi - functional programming interface
 * @export
 */
export const PaymentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaymentsApiAxiosParamCreator(configuration)
    return {
        /**
         * Cancels a payment.  The given payment must have a state of `pending` or `authorized` in order to be canceled.
         * @summary Payment: Cancel
         * @param {string} id A unique identifier for the payment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelPayment(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Payment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelPayment(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.cancelPayment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Captures a payment.  Only works when the payment was created with `capture` set to false, or via a session with `capture` set to `\"manual\"`.
         * @summary Payment: Capture
         * @param {string} id A unique identifier for the payment.
         * @param {CapturePaymentRequest} capturePaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async capturePayment(id: string, capturePaymentRequest: CapturePaymentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Payment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.capturePayment(id, capturePaymentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.capturePayment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a payment for a given `amount` and `currency`.  There are two ways to create payment:  - For one-time payment, you can pass `payment_details` with payment method type and additional attributes. - For recurring payment, you can pass customer\'s ID via `customer` attribute. Customer\'s saved payment method will be used for the payment.  Note that either `payment_details` or `customer` is required for the payment. However, both of them should not be given at the same time.
         * @summary Payment: Create
         * @param {CreatePaymentRequest} createPaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPayment(createPaymentRequest: CreatePaymentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Payment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPayment(createPaymentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.createPayment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * A \"Refund Request\" requests that a payment be refunded manually. This can be used for payment methods that do not support refunds, such as konbini. To support non-refundable payment methods, a bank account must be specified so that we know where to send the funds. Since it is a manual process, the refund will be carried out at a later date, and there\'s a possibility of it being rejected.
         * @summary Payment: Refund Request
         * @param {string} id A unique identifier for the payment.
         * @param {CreateRefundRequestRequest} createRefundRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRefundRequest(id: string, createRefundRequestRequest: CreateRefundRequestRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRefundRequest(id, createRefundRequestRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.createRefundRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Finalizes a payment.  Finalizes an EMV contact transaction by confirming the chip card\'s final decision (TC for approved, AAC for declined). Use this after authorization to submit the terminal\'s transaction outcome and determine whether the payment is captured or cancelled.
         * @summary Payment: Finalize
         * @param {string} id A unique identifier for the payment.
         * @param {FinalizePaymentRequest} finalizePaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async finalizePayment(id: string, finalizePaymentRequest: FinalizePaymentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Payment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.finalizePayment(id, finalizePaymentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.finalizePayment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lists available payment methods.
         * @summary Payment Method: List
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPaymentMethods(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AvailablePaymentMethod>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPaymentMethods(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.listPaymentMethods']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a paginated list of payments. Pagination can be configured with `page` and `per_page` parameters.  Payments can be filtered by `currency`, `external_order_num`, and `status`.  A time range can be specified with `start_time`, and `end_time`.
         * @summary Payment: List
         * @param {string} [startTime] Query for records created after this time.
         * @param {string} [endTime] Query for records created before this time.
         * @param {number} [perPage] How many objects per page.
         * @param {number} [page] Page number to query for.
         * @param {string} [merchantId] 
         * @param {Currency} [currency] 
         * @param {string} [externalOrderNum] A unique ID from your application used to track this payment.
         * @param {string} [status] The status of the payment. Can be a single status or comma-separated values.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPayments(startTime?: string, endTime?: string, perPage?: number, page?: number, merchantId?: string, currency?: Currency, externalOrderNum?: string, status?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPayments(startTime, endTime, perPage, page, merchantId, currency, externalOrderNum, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.listPayments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Refunds an arbitrary amount of money from an existing payment. If no amount is specified, the whole payment is refunded.
         * @summary Payment: Refund
         * @param {string} id A unique identifier for the payment.
         * @param {RefundPaymentRequest} refundPaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refundPayment(id: string, refundPaymentRequest: RefundPaymentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Payment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refundPayment(id, refundPaymentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.refundPayment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a single payment object by its `id`.
         * @summary Payment: Show
         * @param {string} id A unique identifier for the payment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showPayment(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Payment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showPayment(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.showPayment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates a payment.  Only a payment\'s `description` and `metadata` can be changed.
         * @summary Payment: Update
         * @param {string} id A unique identifier for the payment.
         * @param {UpdatePaymentRequest} updatePaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePayment(id: string, updatePaymentRequest: UpdatePaymentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Payment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePayment(id, updatePaymentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.updatePayment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PaymentsApi - factory interface
 * @export
 */
export const PaymentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaymentsApiFp(configuration)
    return {
        /**
         * Cancels a payment.  The given payment must have a state of `pending` or `authorized` in order to be canceled.
         * @summary Payment: Cancel
         * @param {PaymentsApiCancelPaymentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelPayment(requestParameters: PaymentsApiCancelPaymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<Payment> {
            return localVarFp.cancelPayment(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Captures a payment.  Only works when the payment was created with `capture` set to false, or via a session with `capture` set to `\"manual\"`.
         * @summary Payment: Capture
         * @param {PaymentsApiCapturePaymentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        capturePayment(requestParameters: PaymentsApiCapturePaymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<Payment> {
            return localVarFp.capturePayment(requestParameters.id, requestParameters.capturePaymentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a payment for a given `amount` and `currency`.  There are two ways to create payment:  - For one-time payment, you can pass `payment_details` with payment method type and additional attributes. - For recurring payment, you can pass customer\'s ID via `customer` attribute. Customer\'s saved payment method will be used for the payment.  Note that either `payment_details` or `customer` is required for the payment. However, both of them should not be given at the same time.
         * @summary Payment: Create
         * @param {PaymentsApiCreatePaymentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPayment(requestParameters: PaymentsApiCreatePaymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<Payment> {
            return localVarFp.createPayment(requestParameters.createPaymentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * A \"Refund Request\" requests that a payment be refunded manually. This can be used for payment methods that do not support refunds, such as konbini. To support non-refundable payment methods, a bank account must be specified so that we know where to send the funds. Since it is a manual process, the refund will be carried out at a later date, and there\'s a possibility of it being rejected.
         * @summary Payment: Refund Request
         * @param {PaymentsApiCreateRefundRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRefundRequest(requestParameters: PaymentsApiCreateRefundRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createRefundRequest(requestParameters.id, requestParameters.createRefundRequestRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Finalizes a payment.  Finalizes an EMV contact transaction by confirming the chip card\'s final decision (TC for approved, AAC for declined). Use this after authorization to submit the terminal\'s transaction outcome and determine whether the payment is captured or cancelled.
         * @summary Payment: Finalize
         * @param {PaymentsApiFinalizePaymentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        finalizePayment(requestParameters: PaymentsApiFinalizePaymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<Payment> {
            return localVarFp.finalizePayment(requestParameters.id, requestParameters.finalizePaymentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Lists available payment methods.
         * @summary Payment Method: List
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPaymentMethods(options?: RawAxiosRequestConfig): AxiosPromise<Array<AvailablePaymentMethod>> {
            return localVarFp.listPaymentMethods(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a paginated list of payments. Pagination can be configured with `page` and `per_page` parameters.  Payments can be filtered by `currency`, `external_order_num`, and `status`.  A time range can be specified with `start_time`, and `end_time`.
         * @summary Payment: List
         * @param {PaymentsApiListPaymentsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPayments(requestParameters: PaymentsApiListPaymentsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<PaymentList> {
            return localVarFp.listPayments(requestParameters.startTime, requestParameters.endTime, requestParameters.perPage, requestParameters.page, requestParameters.merchantId, requestParameters.currency, requestParameters.externalOrderNum, requestParameters.status, options).then((request) => request(axios, basePath));
        },
        /**
         * Refunds an arbitrary amount of money from an existing payment. If no amount is specified, the whole payment is refunded.
         * @summary Payment: Refund
         * @param {PaymentsApiRefundPaymentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refundPayment(requestParameters: PaymentsApiRefundPaymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<Payment> {
            return localVarFp.refundPayment(requestParameters.id, requestParameters.refundPaymentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a single payment object by its `id`.
         * @summary Payment: Show
         * @param {PaymentsApiShowPaymentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showPayment(requestParameters: PaymentsApiShowPaymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<Payment> {
            return localVarFp.showPayment(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates a payment.  Only a payment\'s `description` and `metadata` can be changed.
         * @summary Payment: Update
         * @param {PaymentsApiUpdatePaymentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePayment(requestParameters: PaymentsApiUpdatePaymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<Payment> {
            return localVarFp.updatePayment(requestParameters.id, requestParameters.updatePaymentRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for cancelPayment operation in PaymentsApi.
 * @export
 * @interface PaymentsApiCancelPaymentRequest
 */
export interface PaymentsApiCancelPaymentRequest {
    /**
     * A unique identifier for the payment.
     * @type {string}
     * @memberof PaymentsApiCancelPayment
     */
    readonly id: string
}

/**
 * Request parameters for capturePayment operation in PaymentsApi.
 * @export
 * @interface PaymentsApiCapturePaymentRequest
 */
export interface PaymentsApiCapturePaymentRequest {
    /**
     * A unique identifier for the payment.
     * @type {string}
     * @memberof PaymentsApiCapturePayment
     */
    readonly id: string

    /**
     * 
     * @type {CapturePaymentRequest}
     * @memberof PaymentsApiCapturePayment
     */
    readonly capturePaymentRequest: CapturePaymentRequest
}

/**
 * Request parameters for createPayment operation in PaymentsApi.
 * @export
 * @interface PaymentsApiCreatePaymentRequest
 */
export interface PaymentsApiCreatePaymentRequest {
    /**
     * 
     * @type {CreatePaymentRequest}
     * @memberof PaymentsApiCreatePayment
     */
    readonly createPaymentRequest: CreatePaymentRequest
}

/**
 * Request parameters for createRefundRequest operation in PaymentsApi.
 * @export
 * @interface PaymentsApiCreateRefundRequestRequest
 */
export interface PaymentsApiCreateRefundRequestRequest {
    /**
     * A unique identifier for the payment.
     * @type {string}
     * @memberof PaymentsApiCreateRefundRequest
     */
    readonly id: string

    /**
     * 
     * @type {CreateRefundRequestRequest}
     * @memberof PaymentsApiCreateRefundRequest
     */
    readonly createRefundRequestRequest: CreateRefundRequestRequest
}

/**
 * Request parameters for finalizePayment operation in PaymentsApi.
 * @export
 * @interface PaymentsApiFinalizePaymentRequest
 */
export interface PaymentsApiFinalizePaymentRequest {
    /**
     * A unique identifier for the payment.
     * @type {string}
     * @memberof PaymentsApiFinalizePayment
     */
    readonly id: string

    /**
     * 
     * @type {FinalizePaymentRequest}
     * @memberof PaymentsApiFinalizePayment
     */
    readonly finalizePaymentRequest: FinalizePaymentRequest
}

/**
 * Request parameters for listPayments operation in PaymentsApi.
 * @export
 * @interface PaymentsApiListPaymentsRequest
 */
export interface PaymentsApiListPaymentsRequest {
    /**
     * Query for records created after this time.
     * @type {string}
     * @memberof PaymentsApiListPayments
     */
    readonly startTime?: string

    /**
     * Query for records created before this time.
     * @type {string}
     * @memberof PaymentsApiListPayments
     */
    readonly endTime?: string

    /**
     * How many objects per page.
     * @type {number}
     * @memberof PaymentsApiListPayments
     */
    readonly perPage?: number

    /**
     * Page number to query for.
     * @type {number}
     * @memberof PaymentsApiListPayments
     */
    readonly page?: number

    /**
     * 
     * @type {string}
     * @memberof PaymentsApiListPayments
     */
    readonly merchantId?: string

    /**
     * 
     * @type {Currency}
     * @memberof PaymentsApiListPayments
     */
    readonly currency?: Currency

    /**
     * A unique ID from your application used to track this payment.
     * @type {string}
     * @memberof PaymentsApiListPayments
     */
    readonly externalOrderNum?: string

    /**
     * The status of the payment. Can be a single status or comma-separated values.
     * @type {string}
     * @memberof PaymentsApiListPayments
     */
    readonly status?: string
}

/**
 * Request parameters for refundPayment operation in PaymentsApi.
 * @export
 * @interface PaymentsApiRefundPaymentRequest
 */
export interface PaymentsApiRefundPaymentRequest {
    /**
     * A unique identifier for the payment.
     * @type {string}
     * @memberof PaymentsApiRefundPayment
     */
    readonly id: string

    /**
     * 
     * @type {RefundPaymentRequest}
     * @memberof PaymentsApiRefundPayment
     */
    readonly refundPaymentRequest: RefundPaymentRequest
}

/**
 * Request parameters for showPayment operation in PaymentsApi.
 * @export
 * @interface PaymentsApiShowPaymentRequest
 */
export interface PaymentsApiShowPaymentRequest {
    /**
     * A unique identifier for the payment.
     * @type {string}
     * @memberof PaymentsApiShowPayment
     */
    readonly id: string
}

/**
 * Request parameters for updatePayment operation in PaymentsApi.
 * @export
 * @interface PaymentsApiUpdatePaymentRequest
 */
export interface PaymentsApiUpdatePaymentRequest {
    /**
     * A unique identifier for the payment.
     * @type {string}
     * @memberof PaymentsApiUpdatePayment
     */
    readonly id: string

    /**
     * 
     * @type {UpdatePaymentRequest}
     * @memberof PaymentsApiUpdatePayment
     */
    readonly updatePaymentRequest: UpdatePaymentRequest
}

/**
 * PaymentsApi - object-oriented interface
 * @export
 * @class PaymentsApi
 * @extends {BaseAPI}
 */
export class PaymentsApi extends BaseAPI {
    /**
     * Cancels a payment.  The given payment must have a state of `pending` or `authorized` in order to be canceled.
     * @summary Payment: Cancel
     * @param {PaymentsApiCancelPaymentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsApi
     */
    public cancelPayment(requestParameters: PaymentsApiCancelPaymentRequest, options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).cancelPayment(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Captures a payment.  Only works when the payment was created with `capture` set to false, or via a session with `capture` set to `\"manual\"`.
     * @summary Payment: Capture
     * @param {PaymentsApiCapturePaymentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsApi
     */
    public capturePayment(requestParameters: PaymentsApiCapturePaymentRequest, options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).capturePayment(requestParameters.id, requestParameters.capturePaymentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a payment for a given `amount` and `currency`.  There are two ways to create payment:  - For one-time payment, you can pass `payment_details` with payment method type and additional attributes. - For recurring payment, you can pass customer\'s ID via `customer` attribute. Customer\'s saved payment method will be used for the payment.  Note that either `payment_details` or `customer` is required for the payment. However, both of them should not be given at the same time.
     * @summary Payment: Create
     * @param {PaymentsApiCreatePaymentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsApi
     */
    public createPayment(requestParameters: PaymentsApiCreatePaymentRequest, options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).createPayment(requestParameters.createPaymentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * A \"Refund Request\" requests that a payment be refunded manually. This can be used for payment methods that do not support refunds, such as konbini. To support non-refundable payment methods, a bank account must be specified so that we know where to send the funds. Since it is a manual process, the refund will be carried out at a later date, and there\'s a possibility of it being rejected.
     * @summary Payment: Refund Request
     * @param {PaymentsApiCreateRefundRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsApi
     */
    public createRefundRequest(requestParameters: PaymentsApiCreateRefundRequestRequest, options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).createRefundRequest(requestParameters.id, requestParameters.createRefundRequestRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Finalizes a payment.  Finalizes an EMV contact transaction by confirming the chip card\'s final decision (TC for approved, AAC for declined). Use this after authorization to submit the terminal\'s transaction outcome and determine whether the payment is captured or cancelled.
     * @summary Payment: Finalize
     * @param {PaymentsApiFinalizePaymentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsApi
     */
    public finalizePayment(requestParameters: PaymentsApiFinalizePaymentRequest, options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).finalizePayment(requestParameters.id, requestParameters.finalizePaymentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lists available payment methods.
     * @summary Payment Method: List
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsApi
     */
    public listPaymentMethods(options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).listPaymentMethods(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a paginated list of payments. Pagination can be configured with `page` and `per_page` parameters.  Payments can be filtered by `currency`, `external_order_num`, and `status`.  A time range can be specified with `start_time`, and `end_time`.
     * @summary Payment: List
     * @param {PaymentsApiListPaymentsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsApi
     */
    public listPayments(requestParameters: PaymentsApiListPaymentsRequest = {}, options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).listPayments(requestParameters.startTime, requestParameters.endTime, requestParameters.perPage, requestParameters.page, requestParameters.merchantId, requestParameters.currency, requestParameters.externalOrderNum, requestParameters.status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Refunds an arbitrary amount of money from an existing payment. If no amount is specified, the whole payment is refunded.
     * @summary Payment: Refund
     * @param {PaymentsApiRefundPaymentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsApi
     */
    public refundPayment(requestParameters: PaymentsApiRefundPaymentRequest, options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).refundPayment(requestParameters.id, requestParameters.refundPaymentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a single payment object by its `id`.
     * @summary Payment: Show
     * @param {PaymentsApiShowPaymentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsApi
     */
    public showPayment(requestParameters: PaymentsApiShowPaymentRequest, options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).showPayment(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates a payment.  Only a payment\'s `description` and `metadata` can be changed.
     * @summary Payment: Update
     * @param {PaymentsApiUpdatePaymentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsApi
     */
    public updatePayment(requestParameters: PaymentsApiUpdatePaymentRequest, options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).updatePayment(requestParameters.id, requestParameters.updatePaymentRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

