/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { APIError } from '../models';
// @ts-ignore
import type { BalanceTransactionList } from '../models';
// @ts-ignore
import type { Currency } from '../models';
// @ts-ignore
import type { SettlementList } from '../models';
// @ts-ignore
import type { SettlementShow } from '../models';
// @ts-ignore
import type { ShowBalance200Response } from '../models';
// @ts-ignore
import type { Transaction } from '../models';
/**
 * SettlementsApi - axios parameter creator
 */
export const SettlementsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Given a currency, view the ledger transactions of the currently authenticated merchant. Will split ledger transactions into line items when appropriate.
         * @summary Balance: Transactions
         * @param {Currency} currency 
         * @param {string} [startTime] Query for records created after this time.
         * @param {string} [endTime] Query for records created before this time.
         * @param {number} [perPage] How many objects per page.
         * @param {number} [page] Page number to query for.
         * @param {string} [type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        balanceTransactions: async (currency: Currency, startTime?: string, endTime?: string, perPage?: number, page?: number, type?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'currency' is not null or undefined
            assertParamExists('balanceTransactions', 'currency', currency)
            const localVarPath = `/balances/{currency}/transactions`
                .replace('{currency}', encodeURIComponent(String(currency)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (startTime !== undefined) {
                localVarQueryParameter['start_time'] = (startTime as any instanceof Date) ?
                    (startTime as any).toISOString() :
                    startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['end_time'] = (endTime as any instanceof Date) ?
                    (endTime as any).toISOString() :
                    endTime;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a paginated list of settlements from most-recent to least-recent. Pagination can be configured with `page` and `per_page` parameters.
         * @summary Settlement: Index
         * @param {string} [startTime] Query for records created after this time.
         * @param {string} [endTime] Query for records created before this time.
         * @param {number} [perPage] How many objects per page.
         * @param {number} [page] Page number to query for.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSettlements: async (startTime?: string, endTime?: string, perPage?: number, page?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/settlements`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (startTime !== undefined) {
                localVarQueryParameter['start_time'] = (startTime as any instanceof Date) ?
                    (startTime as any).toISOString() :
                    startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['end_time'] = (endTime as any instanceof Date) ?
                    (endTime as any).toISOString() :
                    endTime;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Given a currency, view the unsettled balance of the currently authenticated merchant.
         * @summary Balance: Show
         * @param {Currency} currency 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showBalance: async (currency: Currency, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'currency' is not null or undefined
            assertParamExists('showBalance', 'currency', currency)
            const localVarPath = `/balances/{currency}`
                .replace('{currency}', encodeURIComponent(String(currency)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a single settlement by its `id`, including a breakdown of payments, refunds, fees, corrections, and disbursements.
         * @summary Settlement: Show
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showSettlement: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('showSettlement', 'id', id)
            const localVarPath = `/settlements/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the settlement in CSV format.
         * @summary Settlement: CSV
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showSettlementCSV: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('showSettlementCSV', 'id', id)
            const localVarPath = `/settlements/{id}/csv`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the settlement in PDF format.
         * @summary Settlement: PDF
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showSettlementPDF: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('showSettlementPDF', 'id', id)
            const localVarPath = `/settlements/{id}/pdf`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the settlement in XLS format.
         * @summary Settlement: XLS
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showSettlementXLS: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('showSettlementXLS', 'id', id)
            const localVarPath = `/settlements/{id}/xls`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a single ledger transaction by its UUID for the given currency. Will return one entry per line item of the transaction.
         * @summary Balance: Transaction
         * @param {Currency} currency 
         * @param {string} transactionUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showTransaction: async (currency: Currency, transactionUuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'currency' is not null or undefined
            assertParamExists('showTransaction', 'currency', currency)
            // verify required parameter 'transactionUuid' is not null or undefined
            assertParamExists('showTransaction', 'transactionUuid', transactionUuid)
            const localVarPath = `/balances/{currency}/transactions/{transaction_uuid}`
                .replace('{currency}', encodeURIComponent(String(currency)))
                .replace('{transaction_uuid}', encodeURIComponent(String(transactionUuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SettlementsApi - functional programming interface
 */
export const SettlementsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SettlementsApiAxiosParamCreator(configuration)
    return {
        /**
         * Given a currency, view the ledger transactions of the currently authenticated merchant. Will split ledger transactions into line items when appropriate.
         * @summary Balance: Transactions
         * @param {Currency} currency 
         * @param {string} [startTime] Query for records created after this time.
         * @param {string} [endTime] Query for records created before this time.
         * @param {number} [perPage] How many objects per page.
         * @param {number} [page] Page number to query for.
         * @param {string} [type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async balanceTransactions(currency: Currency, startTime?: string, endTime?: string, perPage?: number, page?: number, type?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BalanceTransactionList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.balanceTransactions(currency, startTime, endTime, perPage, page, type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettlementsApi.balanceTransactions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a paginated list of settlements from most-recent to least-recent. Pagination can be configured with `page` and `per_page` parameters.
         * @summary Settlement: Index
         * @param {string} [startTime] Query for records created after this time.
         * @param {string} [endTime] Query for records created before this time.
         * @param {number} [perPage] How many objects per page.
         * @param {number} [page] Page number to query for.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSettlements(startTime?: string, endTime?: string, perPage?: number, page?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SettlementList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSettlements(startTime, endTime, perPage, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettlementsApi.listSettlements']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Given a currency, view the unsettled balance of the currently authenticated merchant.
         * @summary Balance: Show
         * @param {Currency} currency 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showBalance(currency: Currency, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ShowBalance200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showBalance(currency, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettlementsApi.showBalance']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a single settlement by its `id`, including a breakdown of payments, refunds, fees, corrections, and disbursements.
         * @summary Settlement: Show
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showSettlement(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SettlementShow>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showSettlement(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettlementsApi.showSettlement']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves the settlement in CSV format.
         * @summary Settlement: CSV
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showSettlementCSV(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showSettlementCSV(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettlementsApi.showSettlementCSV']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves the settlement in PDF format.
         * @summary Settlement: PDF
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showSettlementPDF(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showSettlementPDF(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettlementsApi.showSettlementPDF']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves the settlement in XLS format.
         * @summary Settlement: XLS
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showSettlementXLS(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showSettlementXLS(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettlementsApi.showSettlementXLS']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a single ledger transaction by its UUID for the given currency. Will return one entry per line item of the transaction.
         * @summary Balance: Transaction
         * @param {Currency} currency 
         * @param {string} transactionUuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showTransaction(currency: Currency, transactionUuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Transaction>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showTransaction(currency, transactionUuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettlementsApi.showTransaction']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SettlementsApi - factory interface
 */
export const SettlementsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SettlementsApiFp(configuration)
    return {
        /**
         * Given a currency, view the ledger transactions of the currently authenticated merchant. Will split ledger transactions into line items when appropriate.
         * @summary Balance: Transactions
         * @param {SettlementsApiBalanceTransactionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        balanceTransactions(requestParameters: SettlementsApiBalanceTransactionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<BalanceTransactionList> {
            return localVarFp.balanceTransactions(requestParameters.currency, requestParameters.startTime, requestParameters.endTime, requestParameters.perPage, requestParameters.page, requestParameters.type, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a paginated list of settlements from most-recent to least-recent. Pagination can be configured with `page` and `per_page` parameters.
         * @summary Settlement: Index
         * @param {SettlementsApiListSettlementsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSettlements(requestParameters: SettlementsApiListSettlementsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<SettlementList> {
            return localVarFp.listSettlements(requestParameters.startTime, requestParameters.endTime, requestParameters.perPage, requestParameters.page, options).then((request) => request(axios, basePath));
        },
        /**
         * Given a currency, view the unsettled balance of the currently authenticated merchant.
         * @summary Balance: Show
         * @param {SettlementsApiShowBalanceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showBalance(requestParameters: SettlementsApiShowBalanceRequest, options?: RawAxiosRequestConfig): AxiosPromise<ShowBalance200Response> {
            return localVarFp.showBalance(requestParameters.currency, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a single settlement by its `id`, including a breakdown of payments, refunds, fees, corrections, and disbursements.
         * @summary Settlement: Show
         * @param {SettlementsApiShowSettlementRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showSettlement(requestParameters: SettlementsApiShowSettlementRequest, options?: RawAxiosRequestConfig): AxiosPromise<SettlementShow> {
            return localVarFp.showSettlement(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the settlement in CSV format.
         * @summary Settlement: CSV
         * @param {SettlementsApiShowSettlementCSVRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showSettlementCSV(requestParameters: SettlementsApiShowSettlementCSVRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.showSettlementCSV(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the settlement in PDF format.
         * @summary Settlement: PDF
         * @param {SettlementsApiShowSettlementPDFRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showSettlementPDF(requestParameters: SettlementsApiShowSettlementPDFRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.showSettlementPDF(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the settlement in XLS format.
         * @summary Settlement: XLS
         * @param {SettlementsApiShowSettlementXLSRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showSettlementXLS(requestParameters: SettlementsApiShowSettlementXLSRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.showSettlementXLS(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a single ledger transaction by its UUID for the given currency. Will return one entry per line item of the transaction.
         * @summary Balance: Transaction
         * @param {SettlementsApiShowTransactionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showTransaction(requestParameters: SettlementsApiShowTransactionRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<Transaction>> {
            return localVarFp.showTransaction(requestParameters.currency, requestParameters.transactionUuid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for balanceTransactions operation in SettlementsApi.
 */
export interface SettlementsApiBalanceTransactionsRequest {
    readonly currency: Currency

    /**
     * Query for records created after this time.
     */
    readonly startTime?: string

    /**
     * Query for records created before this time.
     */
    readonly endTime?: string

    /**
     * How many objects per page.
     */
    readonly perPage?: number

    /**
     * Page number to query for.
     */
    readonly page?: number

    readonly type?: string
}

/**
 * Request parameters for listSettlements operation in SettlementsApi.
 */
export interface SettlementsApiListSettlementsRequest {
    /**
     * Query for records created after this time.
     */
    readonly startTime?: string

    /**
     * Query for records created before this time.
     */
    readonly endTime?: string

    /**
     * How many objects per page.
     */
    readonly perPage?: number

    /**
     * Page number to query for.
     */
    readonly page?: number
}

/**
 * Request parameters for showBalance operation in SettlementsApi.
 */
export interface SettlementsApiShowBalanceRequest {
    readonly currency: Currency
}

/**
 * Request parameters for showSettlement operation in SettlementsApi.
 */
export interface SettlementsApiShowSettlementRequest {
    readonly id: string
}

/**
 * Request parameters for showSettlementCSV operation in SettlementsApi.
 */
export interface SettlementsApiShowSettlementCSVRequest {
    readonly id: string
}

/**
 * Request parameters for showSettlementPDF operation in SettlementsApi.
 */
export interface SettlementsApiShowSettlementPDFRequest {
    readonly id: string
}

/**
 * Request parameters for showSettlementXLS operation in SettlementsApi.
 */
export interface SettlementsApiShowSettlementXLSRequest {
    readonly id: string
}

/**
 * Request parameters for showTransaction operation in SettlementsApi.
 */
export interface SettlementsApiShowTransactionRequest {
    readonly currency: Currency

    readonly transactionUuid: string
}

/**
 * SettlementsApi - object-oriented interface
 */
export class SettlementsApi extends BaseAPI {
    /**
     * Given a currency, view the ledger transactions of the currently authenticated merchant. Will split ledger transactions into line items when appropriate.
     * @summary Balance: Transactions
     * @param {SettlementsApiBalanceTransactionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public balanceTransactions(requestParameters: SettlementsApiBalanceTransactionsRequest, options?: RawAxiosRequestConfig) {
        return SettlementsApiFp(this.configuration).balanceTransactions(requestParameters.currency, requestParameters.startTime, requestParameters.endTime, requestParameters.perPage, requestParameters.page, requestParameters.type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a paginated list of settlements from most-recent to least-recent. Pagination can be configured with `page` and `per_page` parameters.
     * @summary Settlement: Index
     * @param {SettlementsApiListSettlementsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listSettlements(requestParameters: SettlementsApiListSettlementsRequest = {}, options?: RawAxiosRequestConfig) {
        return SettlementsApiFp(this.configuration).listSettlements(requestParameters.startTime, requestParameters.endTime, requestParameters.perPage, requestParameters.page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Given a currency, view the unsettled balance of the currently authenticated merchant.
     * @summary Balance: Show
     * @param {SettlementsApiShowBalanceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public showBalance(requestParameters: SettlementsApiShowBalanceRequest, options?: RawAxiosRequestConfig) {
        return SettlementsApiFp(this.configuration).showBalance(requestParameters.currency, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a single settlement by its `id`, including a breakdown of payments, refunds, fees, corrections, and disbursements.
     * @summary Settlement: Show
     * @param {SettlementsApiShowSettlementRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public showSettlement(requestParameters: SettlementsApiShowSettlementRequest, options?: RawAxiosRequestConfig) {
        return SettlementsApiFp(this.configuration).showSettlement(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the settlement in CSV format.
     * @summary Settlement: CSV
     * @param {SettlementsApiShowSettlementCSVRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public showSettlementCSV(requestParameters: SettlementsApiShowSettlementCSVRequest, options?: RawAxiosRequestConfig) {
        return SettlementsApiFp(this.configuration).showSettlementCSV(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the settlement in PDF format.
     * @summary Settlement: PDF
     * @param {SettlementsApiShowSettlementPDFRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public showSettlementPDF(requestParameters: SettlementsApiShowSettlementPDFRequest, options?: RawAxiosRequestConfig) {
        return SettlementsApiFp(this.configuration).showSettlementPDF(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the settlement in XLS format.
     * @summary Settlement: XLS
     * @param {SettlementsApiShowSettlementXLSRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public showSettlementXLS(requestParameters: SettlementsApiShowSettlementXLSRequest, options?: RawAxiosRequestConfig) {
        return SettlementsApiFp(this.configuration).showSettlementXLS(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a single ledger transaction by its UUID for the given currency. Will return one entry per line item of the transaction.
     * @summary Balance: Transaction
     * @param {SettlementsApiShowTransactionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public showTransaction(requestParameters: SettlementsApiShowTransactionRequest, options?: RawAxiosRequestConfig) {
        return SettlementsApiFp(this.configuration).showTransaction(requestParameters.currency, requestParameters.transactionUuid, options).then((request) => request(this.axios, this.basePath));
    }
}

