/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateCustomerRequest } from '../models';
// @ts-ignore
import type { CreateSubscriptionRequest } from '../models';
// @ts-ignore
import type { Customer } from '../models';
// @ts-ignore
import type { CustomerList } from '../models';
// @ts-ignore
import type { Subscription } from '../models';
// @ts-ignore
import type { SubscriptionList } from '../models';
// @ts-ignore
import type { UpdateCustomerRequest } from '../models';
/**
 * SubscriptionsApi - axios parameter creator
 */
export const SubscriptionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new customer with the specified `payment_details`. Customer payment details are stored in a secure, PCI DSS-compliant way.  Once you have a customer, you may specify the customer\'s `id` instead of `payment_details` when creating a payment.
         * @summary Customer: Create
         * @param {CreateCustomerRequest} createCustomerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCustomer: async (createCustomerRequest: CreateCustomerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createCustomerRequest' is not null or undefined
            assertParamExists('createCustomer', 'createCustomerRequest', createCustomerRequest)
            const localVarPath = `/customers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCustomerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new subscription. A subscription represents a recurring payment. Recurring payments may be on a `weekly`, `monthly`, or `yearly` basis, specified by the period parameter.  In order to create a subscription, a customer ID must be supplied. The customer object contains saved payment info, which is regularly charged by the subscription.  A subscription can\'t be modified once it\'s created. To change a subscription, you must delete it and create a new one.
         * @summary Subscription: Create
         * @param {CreateSubscriptionRequest} createSubscriptionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSubscription: async (createSubscriptionRequest: CreateSubscriptionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createSubscriptionRequest' is not null or undefined
            assertParamExists('createSubscription', 'createSubscriptionRequest', createSubscriptionRequest)
            const localVarPath = `/subscriptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSubscriptionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes the customer with the given `id`. This complete erases the stored payment details from our database.
         * @summary Customer: Destroy
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCustomer: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteCustomer', 'id', id)
            const localVarPath = `/customers/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a subscription. Once deleted, the subscription\'s regular payments will stop.
         * @summary Subscription: Destroy
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubscription: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteSubscription', 'id', id)
            const localVarPath = `/subscriptions/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a paginated list of all previously-registered customers.
         * @summary Customer: List
         * @param {string} [startTime] Query for records created after this time.
         * @param {string} [endTime] Query for records created before this time.
         * @param {number} [perPage] How many objects per page.
         * @param {number} [page] Page number to query for.
         * @param {string} [expiration] The expiration of the customer\&#39;s credit card in MMYY format.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCustomers: async (startTime?: string, endTime?: string, perPage?: number, page?: number, expiration?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/customers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (startTime !== undefined) {
                localVarQueryParameter['start_time'] = (startTime as any instanceof Date) ?
                    (startTime as any).toISOString() :
                    startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['end_time'] = (endTime as any instanceof Date) ?
                    (endTime as any).toISOString() :
                    endTime;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (expiration !== undefined) {
                localVarQueryParameter['expiration'] = expiration;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List existing subscriptions.
         * @summary Subscription: List
         * @param {string} [startTime] Query for records created after this time.
         * @param {string} [endTime] Query for records created before this time.
         * @param {number} [perPage] How many objects per page.
         * @param {number} [page] Page number to query for.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSubscriptions: async (startTime?: string, endTime?: string, perPage?: number, page?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/subscriptions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (startTime !== undefined) {
                localVarQueryParameter['start_time'] = (startTime as any instanceof Date) ?
                    (startTime as any).toISOString() :
                    startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['end_time'] = (endTime as any instanceof Date) ?
                    (endTime as any).toISOString() :
                    endTime;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves customer personal information.
         * @summary Customer: Show
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showCustomer: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('showCustomer', 'id', id)
            const localVarPath = `/customers/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Show an existing subscription, including its customer and scrubbed payment details.
         * @summary Subscription: Show
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showSubscription: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('showSubscription', 'id', id)
            const localVarPath = `/subscriptions/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates the customer with the given `id`. A new set of `payment_details` may be specified.
         * @summary Customer: Update
         * @param {string} id 
         * @param {UpdateCustomerRequest} updateCustomerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCustomer: async (id: string, updateCustomerRequest: UpdateCustomerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateCustomer', 'id', id)
            // verify required parameter 'updateCustomerRequest' is not null or undefined
            assertParamExists('updateCustomer', 'updateCustomerRequest', updateCustomerRequest)
            const localVarPath = `/customers/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCustomerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SubscriptionsApi - functional programming interface
 */
export const SubscriptionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SubscriptionsApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a new customer with the specified `payment_details`. Customer payment details are stored in a secure, PCI DSS-compliant way.  Once you have a customer, you may specify the customer\'s `id` instead of `payment_details` when creating a payment.
         * @summary Customer: Create
         * @param {CreateCustomerRequest} createCustomerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCustomer(createCustomerRequest: CreateCustomerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Customer>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCustomer(createCustomerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.createCustomer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new subscription. A subscription represents a recurring payment. Recurring payments may be on a `weekly`, `monthly`, or `yearly` basis, specified by the period parameter.  In order to create a subscription, a customer ID must be supplied. The customer object contains saved payment info, which is regularly charged by the subscription.  A subscription can\'t be modified once it\'s created. To change a subscription, you must delete it and create a new one.
         * @summary Subscription: Create
         * @param {CreateSubscriptionRequest} createSubscriptionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSubscription(createSubscriptionRequest: CreateSubscriptionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSubscription(createSubscriptionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.createSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes the customer with the given `id`. This complete erases the stored payment details from our database.
         * @summary Customer: Destroy
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCustomer(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Customer>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCustomer(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.deleteCustomer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a subscription. Once deleted, the subscription\'s regular payments will stop.
         * @summary Subscription: Destroy
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSubscription(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSubscription(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.deleteSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a paginated list of all previously-registered customers.
         * @summary Customer: List
         * @param {string} [startTime] Query for records created after this time.
         * @param {string} [endTime] Query for records created before this time.
         * @param {number} [perPage] How many objects per page.
         * @param {number} [page] Page number to query for.
         * @param {string} [expiration] The expiration of the customer\&#39;s credit card in MMYY format.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCustomers(startTime?: string, endTime?: string, perPage?: number, page?: number, expiration?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustomerList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listCustomers(startTime, endTime, perPage, page, expiration, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.listCustomers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List existing subscriptions.
         * @summary Subscription: List
         * @param {string} [startTime] Query for records created after this time.
         * @param {string} [endTime] Query for records created before this time.
         * @param {number} [perPage] How many objects per page.
         * @param {number} [page] Page number to query for.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSubscriptions(startTime?: string, endTime?: string, perPage?: number, page?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSubscriptions(startTime, endTime, perPage, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.listSubscriptions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves customer personal information.
         * @summary Customer: Show
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showCustomer(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Customer>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showCustomer(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.showCustomer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Show an existing subscription, including its customer and scrubbed payment details.
         * @summary Subscription: Show
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async showSubscription(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Subscription>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.showSubscription(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.showSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates the customer with the given `id`. A new set of `payment_details` may be specified.
         * @summary Customer: Update
         * @param {string} id 
         * @param {UpdateCustomerRequest} updateCustomerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCustomer(id: string, updateCustomerRequest: UpdateCustomerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Customer>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCustomer(id, updateCustomerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionsApi.updateCustomer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SubscriptionsApi - factory interface
 */
export const SubscriptionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SubscriptionsApiFp(configuration)
    return {
        /**
         * Creates a new customer with the specified `payment_details`. Customer payment details are stored in a secure, PCI DSS-compliant way.  Once you have a customer, you may specify the customer\'s `id` instead of `payment_details` when creating a payment.
         * @summary Customer: Create
         * @param {SubscriptionsApiCreateCustomerRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCustomer(requestParameters: SubscriptionsApiCreateCustomerRequest, options?: RawAxiosRequestConfig): AxiosPromise<Customer> {
            return localVarFp.createCustomer(requestParameters.createCustomerRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new subscription. A subscription represents a recurring payment. Recurring payments may be on a `weekly`, `monthly`, or `yearly` basis, specified by the period parameter.  In order to create a subscription, a customer ID must be supplied. The customer object contains saved payment info, which is regularly charged by the subscription.  A subscription can\'t be modified once it\'s created. To change a subscription, you must delete it and create a new one.
         * @summary Subscription: Create
         * @param {SubscriptionsApiCreateSubscriptionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSubscription(requestParameters: SubscriptionsApiCreateSubscriptionRequest, options?: RawAxiosRequestConfig): AxiosPromise<Subscription> {
            return localVarFp.createSubscription(requestParameters.createSubscriptionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes the customer with the given `id`. This complete erases the stored payment details from our database.
         * @summary Customer: Destroy
         * @param {SubscriptionsApiDeleteCustomerRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCustomer(requestParameters: SubscriptionsApiDeleteCustomerRequest, options?: RawAxiosRequestConfig): AxiosPromise<Customer> {
            return localVarFp.deleteCustomer(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a subscription. Once deleted, the subscription\'s regular payments will stop.
         * @summary Subscription: Destroy
         * @param {SubscriptionsApiDeleteSubscriptionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSubscription(requestParameters: SubscriptionsApiDeleteSubscriptionRequest, options?: RawAxiosRequestConfig): AxiosPromise<Subscription> {
            return localVarFp.deleteSubscription(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a paginated list of all previously-registered customers.
         * @summary Customer: List
         * @param {SubscriptionsApiListCustomersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCustomers(requestParameters: SubscriptionsApiListCustomersRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CustomerList> {
            return localVarFp.listCustomers(requestParameters.startTime, requestParameters.endTime, requestParameters.perPage, requestParameters.page, requestParameters.expiration, options).then((request) => request(axios, basePath));
        },
        /**
         * List existing subscriptions.
         * @summary Subscription: List
         * @param {SubscriptionsApiListSubscriptionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSubscriptions(requestParameters: SubscriptionsApiListSubscriptionsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionList> {
            return localVarFp.listSubscriptions(requestParameters.startTime, requestParameters.endTime, requestParameters.perPage, requestParameters.page, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves customer personal information.
         * @summary Customer: Show
         * @param {SubscriptionsApiShowCustomerRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showCustomer(requestParameters: SubscriptionsApiShowCustomerRequest, options?: RawAxiosRequestConfig): AxiosPromise<Customer> {
            return localVarFp.showCustomer(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Show an existing subscription, including its customer and scrubbed payment details.
         * @summary Subscription: Show
         * @param {SubscriptionsApiShowSubscriptionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        showSubscription(requestParameters: SubscriptionsApiShowSubscriptionRequest, options?: RawAxiosRequestConfig): AxiosPromise<Subscription> {
            return localVarFp.showSubscription(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates the customer with the given `id`. A new set of `payment_details` may be specified.
         * @summary Customer: Update
         * @param {SubscriptionsApiUpdateCustomerRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCustomer(requestParameters: SubscriptionsApiUpdateCustomerRequest, options?: RawAxiosRequestConfig): AxiosPromise<Customer> {
            return localVarFp.updateCustomer(requestParameters.id, requestParameters.updateCustomerRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createCustomer operation in SubscriptionsApi.
 */
export interface SubscriptionsApiCreateCustomerRequest {
    readonly createCustomerRequest: CreateCustomerRequest
}

/**
 * Request parameters for createSubscription operation in SubscriptionsApi.
 */
export interface SubscriptionsApiCreateSubscriptionRequest {
    readonly createSubscriptionRequest: CreateSubscriptionRequest
}

/**
 * Request parameters for deleteCustomer operation in SubscriptionsApi.
 */
export interface SubscriptionsApiDeleteCustomerRequest {
    readonly id: string
}

/**
 * Request parameters for deleteSubscription operation in SubscriptionsApi.
 */
export interface SubscriptionsApiDeleteSubscriptionRequest {
    readonly id: string
}

/**
 * Request parameters for listCustomers operation in SubscriptionsApi.
 */
export interface SubscriptionsApiListCustomersRequest {
    /**
     * Query for records created after this time.
     */
    readonly startTime?: string

    /**
     * Query for records created before this time.
     */
    readonly endTime?: string

    /**
     * How many objects per page.
     */
    readonly perPage?: number

    /**
     * Page number to query for.
     */
    readonly page?: number

    /**
     * The expiration of the customer\&#39;s credit card in MMYY format.
     */
    readonly expiration?: string
}

/**
 * Request parameters for listSubscriptions operation in SubscriptionsApi.
 */
export interface SubscriptionsApiListSubscriptionsRequest {
    /**
     * Query for records created after this time.
     */
    readonly startTime?: string

    /**
     * Query for records created before this time.
     */
    readonly endTime?: string

    /**
     * How many objects per page.
     */
    readonly perPage?: number

    /**
     * Page number to query for.
     */
    readonly page?: number
}

/**
 * Request parameters for showCustomer operation in SubscriptionsApi.
 */
export interface SubscriptionsApiShowCustomerRequest {
    readonly id: string
}

/**
 * Request parameters for showSubscription operation in SubscriptionsApi.
 */
export interface SubscriptionsApiShowSubscriptionRequest {
    readonly id: string
}

/**
 * Request parameters for updateCustomer operation in SubscriptionsApi.
 */
export interface SubscriptionsApiUpdateCustomerRequest {
    readonly id: string

    readonly updateCustomerRequest: UpdateCustomerRequest
}

/**
 * SubscriptionsApi - object-oriented interface
 */
export class SubscriptionsApi extends BaseAPI {
    /**
     * Creates a new customer with the specified `payment_details`. Customer payment details are stored in a secure, PCI DSS-compliant way.  Once you have a customer, you may specify the customer\'s `id` instead of `payment_details` when creating a payment.
     * @summary Customer: Create
     * @param {SubscriptionsApiCreateCustomerRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createCustomer(requestParameters: SubscriptionsApiCreateCustomerRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).createCustomer(requestParameters.createCustomerRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new subscription. A subscription represents a recurring payment. Recurring payments may be on a `weekly`, `monthly`, or `yearly` basis, specified by the period parameter.  In order to create a subscription, a customer ID must be supplied. The customer object contains saved payment info, which is regularly charged by the subscription.  A subscription can\'t be modified once it\'s created. To change a subscription, you must delete it and create a new one.
     * @summary Subscription: Create
     * @param {SubscriptionsApiCreateSubscriptionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSubscription(requestParameters: SubscriptionsApiCreateSubscriptionRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).createSubscription(requestParameters.createSubscriptionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes the customer with the given `id`. This complete erases the stored payment details from our database.
     * @summary Customer: Destroy
     * @param {SubscriptionsApiDeleteCustomerRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteCustomer(requestParameters: SubscriptionsApiDeleteCustomerRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).deleteCustomer(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a subscription. Once deleted, the subscription\'s regular payments will stop.
     * @summary Subscription: Destroy
     * @param {SubscriptionsApiDeleteSubscriptionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteSubscription(requestParameters: SubscriptionsApiDeleteSubscriptionRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).deleteSubscription(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a paginated list of all previously-registered customers.
     * @summary Customer: List
     * @param {SubscriptionsApiListCustomersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listCustomers(requestParameters: SubscriptionsApiListCustomersRequest = {}, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).listCustomers(requestParameters.startTime, requestParameters.endTime, requestParameters.perPage, requestParameters.page, requestParameters.expiration, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List existing subscriptions.
     * @summary Subscription: List
     * @param {SubscriptionsApiListSubscriptionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listSubscriptions(requestParameters: SubscriptionsApiListSubscriptionsRequest = {}, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).listSubscriptions(requestParameters.startTime, requestParameters.endTime, requestParameters.perPage, requestParameters.page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves customer personal information.
     * @summary Customer: Show
     * @param {SubscriptionsApiShowCustomerRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public showCustomer(requestParameters: SubscriptionsApiShowCustomerRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).showCustomer(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Show an existing subscription, including its customer and scrubbed payment details.
     * @summary Subscription: Show
     * @param {SubscriptionsApiShowSubscriptionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public showSubscription(requestParameters: SubscriptionsApiShowSubscriptionRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).showSubscription(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates the customer with the given `id`. A new set of `payment_details` may be specified.
     * @summary Customer: Update
     * @param {SubscriptionsApiUpdateCustomerRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateCustomer(requestParameters: SubscriptionsApiUpdateCustomerRequest, options?: RawAxiosRequestConfig) {
        return SubscriptionsApiFp(this.configuration).updateCustomer(requestParameters.id, requestParameters.updateCustomerRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

