/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AvailablePaymentMethod
 */
export interface AvailablePaymentMethod {
    /**
     * English display name of the payment method.
     * @type {string}
     * @memberof AvailablePaymentMethod
     */
    'name_en': string;
    /**
     * Japanese display name of the payment method.
     * @type {string}
     * @memberof AvailablePaymentMethod
     */
    'name_ja': string;
    /**
     * Korean display name of the payment method.
     * @type {string}
     * @memberof AvailablePaymentMethod
     */
    'name_ko': string;
    /**
     * Machine-readable type identifier for the payment method.
     * @type {string}
     * @memberof AvailablePaymentMethod
     */
    'type_slug': string;
    /**
     * Currency this payment method supports.
     * @type {string}
     * @memberof AvailablePaymentMethod
     */
    'currency': string;
    /**
     * Optional list of subtypes or variants (e.g. card brands).
     * @type {Array<string>}
     * @memberof AvailablePaymentMethod
     */
    'subtypes'?: Array<string>;
    /**
     * Optional list of secure token / 3DS flows supported by this payment method.
     * @type {Array<string>}
     * @memberof AvailablePaymentMethod
     */
    'secure_token_supported'?: Array<string>;
}

