/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BarcodePendingResponse
 */
export interface BarcodePendingResponse {
    /**
     * Barcode generation is pending
     * @type {string}
     * @memberof BarcodePendingResponse
     */
    'status': BarcodePendingResponseStatusEnum;
    /**
     * Request may be retried after specified amount of seconds
     * @type {number}
     * @memberof BarcodePendingResponse
     */
    'retry_after': number;
}

/**
    * @export
    * @enum {string}
    */
export enum BarcodePendingResponseStatusEnum {
    Pending = 'pending'
}


