/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Recipient details as stored on a submitted defense. Fields may be null.
 */
export interface ChargebackDefenseRecipientInfo {
    /**
     * Recipient\'s name, or null.
     */
    'name': string | null;
    /**
     * Recipient\'s phone number, or null.
     */
    'phone': string | null;
    /**
     * Recipient\'s email address, or null.
     */
    'email': string | null;
}

