/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChargebackPaymentMethod } from './chargeback-payment-method';
// May contain unused imports in some cases
// @ts-ignore
import type { ChargebackStatus } from './chargeback-status';
// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';

export interface ChargebackRequestListItem {
    /**
     * A unique 25-character alphanumeric resource identifier.
     */
    'id': string;
    /**
     * A unique 25-character alphanumeric resource identifier.
     */
    'payment_id': string;
    /**
     * Amount greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
     */
    'amount': number;
    'currency': Currency;
    'payment_method': ChargebackPaymentMethod;
    /**
     * Machine-readable reason code. Internal codes (e.g. \"CB_Fraud\") are used by default; for Worldpay Visa/Mastercard payments the network\'s own reason codes are used instead (e.g. \"10.4\" or \"4837\").
     */
    'reason_code': string;
    /**
     * Human-readable chargeback reason corresponding to the reason code.
     */
    'reason': string;
    /**
     * Timestamp when the chargeback was created.
     */
    'created_at': string;
    /**
     * Deadline by which the merchant must respond.
     */
    'due_date': string;
    'status': ChargebackStatus;
}



