/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Summary of the payment method associated with a chargeback.
 */
export interface ChargebackPaymentMethod {
    /**
     * Payment method type slug (e.g. \"credit_card\").
     */
    'type': string;
    /**
     * Card brand, or null if not applicable.
     */
    'brand': string | null;
    /**
     * Last four digits of the card, or null if not applicable.
     */
    'last_four_digits': string | null;
}

