/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Current status of a chargeback request.
 */

export enum ChargebackStatus {
    Pending = 'pending',
    Accepted = 'accepted',
    Cancelled = 'cancelled',
    Expired = 'expired',
    Defended = 'defended',
    Lost = 'lost'
}



