/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateSecureTokenRequestWithCustomer } from './create-secure-token-request-with-customer';
// May contain unused imports in some cases
// @ts-ignore
import type { CreateSecureTokenRequestWithPaymentDetails } from './create-secure-token-request-with-payment-details';
// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentDetailsOnlyCreditCards } from './payment-details-only-credit-cards';
// May contain unused imports in some cases
// @ts-ignore
import type { ProcessingMerchant } from './processing-merchant';

/**
 * @type CreateSecureTokenRequest
 */
export type CreateSecureTokenRequest = CreateSecureTokenRequestWithCustomer | CreateSecureTokenRequestWithPaymentDetails;


