/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentDetailsOnlyCreditCards } from './payment-details-only-credit-cards';
// May contain unused imports in some cases
// @ts-ignore
import type { ProcessingMerchant } from './processing-merchant';

/**
 * 
 * @export
 * @interface CreateSecureTokenRequestWithPaymentDetails
 */
export interface CreateSecureTokenRequestWithPaymentDetails {
    /**
     * Amount greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
     * @type {number}
     * @memberof CreateSecureTokenRequestWithPaymentDetails
     */
    'amount': number;
    /**
     * 
     * @type {Currency}
     * @memberof CreateSecureTokenRequestWithPaymentDetails
     */
    'currency': Currency;
    /**
     * 
     * @type {PaymentDetailsOnlyCreditCards}
     * @memberof CreateSecureTokenRequestWithPaymentDetails
     */
    'payment_details': PaymentDetailsOnlyCreditCards;
    /**
     * 
     * @type {string}
     * @memberof CreateSecureTokenRequestWithPaymentDetails
     */
    'return_url': string;
    /**
     * 
     * @type {ProcessingMerchant}
     * @memberof CreateSecureTokenRequestWithPaymentDetails
     */
    'platform_details'?: ProcessingMerchant;
}



