/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionPeriod } from './subscription-period';

export interface CreateSubscriptionRequest {
    /**
     * A unique 25-character alphanumeric resource identifier.
     */
    'customer': string;
    /**
     * Amount greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
     */
    'amount': number;
    'currency': Currency;
    'period': SubscriptionPeriod;
    /**
     * Store any additional data you want to associate with the subscription. The object\'s keys and values must be strings. Keys have a maximum length of 30 characters. Values have a maximum length of 2000 characters.
     */
    'metadata'?: object;
}



