/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentDetailsOnlyCreditCards } from './payment-details-only-credit-cards';

/**
 * 
 * @export
 * @interface CreateCustomerRequest
 */
export interface CreateCustomerRequest {
    /**
     * 
     * @type {Currency}
     * @memberof CreateCustomerRequest
     */
    'currency'?: Currency;
    /**
     * 
     * @type {PaymentDetailsOnlyCreditCards}
     * @memberof CreateCustomerRequest
     */
    'payment_details'?: PaymentDetailsOnlyCreditCards;
    /**
     * Customer\'s email address.
     * @type {string}
     * @memberof CreateCustomerRequest
     */
    'email'?: string;
    /**
     * Store any additional data you want to associate with the customer. The object\'s keys and values must be strings. Keys have a maximum length of 30 characters. Values have a maximum length of 2000 characters.
     * @type {object}
     * @memberof CreateCustomerRequest
     */
    'metadata'?: object;
}



