/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomerSource } from './customer-source';
// May contain unused imports in some cases
// @ts-ignore
import type { Locale } from './locale';

export interface Customer {
    /**
     * A unique 25-character alphanumeric resource identifier.
     */
    'id': string;
    /**
     * Resource type name, always \"customer\".
     */
    'resource': CustomerResourceEnum;
    /**
     * Customer\'s email address, or null if not provided.
     */
    'email': string | null;
    'source': CustomerSource | null;
    /**
     * Arbitrary key-value metadata attached to this customer.
     */
    'metadata': object;
    /**
     * Timestamp when the customer was created.
     */
    'created_at': string;
    'locale'?: Locale;
}

export enum CustomerResourceEnum {
    Customer = 'customer'
}


