/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Saved payment source for this customer, or null if none is saved.
 */
export interface CustomerSource {
    /**
     * Payment method type of the saved payment source.
     */
    'type': string;
    /**
     * Card brand (e.g. \"visa\", \"mastercard\").
     */
    'brand': string;
    /**
     * Last four digits of the saved card.
     */
    'last_four_digits': string;
    /**
     * Card expiry month (two digits).
     */
    'month': number;
    /**
     * Card expiry year (two or four digits).
     */
    'year': number;
}

