/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Customer } from './customer';

export interface CustomerList {
    /**
     * Resource type name, always \"customer_list\".
     */
    'resource': string;
    /**
     * Array of customer objects for this page.
     */
    'data': Array<Customer>;
    /**
     * Start of the time range for records in this response.
     */
    'start_time': string;
    /**
     * End of the time range for records in this response.
     */
    'end_time': string;
    /**
     * Total number of records matching the query.
     */
    'total': number;
    /**
     * Current page number.
     */
    'page': number;
    /**
     * Number of results per page.
     */
    'per_page': number;
    /**
     * Last available page number.
     */
    'last_page': number;
}

