/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FieldFieldProperties
 */
export interface FieldFieldProperties {
    /**
     * Array of URLs to external resources relevant to this field.
     * @type {Array<string>}
     * @memberof FieldFieldProperties
     */
    'external_links': Array<string>;
    /**
     * Minimum character length for the field value.
     * @type {number}
     * @memberof FieldFieldProperties
     */
    'minLength': number;
}

