/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FieldFieldProperties } from './field-field-properties';

export interface Field {
    /**
     * The input type for this field (e.g. \"text\", \"file\", \"boolean\").
     */
    'field_type': string;
    /**
     * Machine-readable key name of the field.
     */
    'field': string;
    /**
     * Human-readable display name of the field.
     */
    'field_name': string;
    'field_properties': FieldFieldProperties;
    /**
     * Display order position of this field in the application form.
     */
    'position': number;
    /**
     * Whether this field is optional (true) or required (false).
     */
    'optional': boolean;
}

