/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface FinalizePaymentRequest {
    'capture'?: boolean;
    /**
     * EMV chip card action code: TC (approved), AAC (declined), or fault.
     */
    'ac_type': FinalizePaymentRequestAcTypeEnum;
    /**
     * EMV tag 55 data from the chip card transaction.
     */
    'field55': string;
    /**
     * Track 2 magnetic stripe equivalent data from the chip card.
     */
    'track2': string;
    'metadata'?: object;
}

export enum FinalizePaymentRequestAcTypeEnum {
    Tc = 'tc',
    Aac = 'aac',
    Fault = 'fault'
}


