/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Specify customer\'s personal information to help us determine the legitimacy of the payment. It\'s recommended to include this information whenever possible to reduce the number of chargebacks.  See [Fraud Details](https://doc.komoju.com/docs/fraud-details) for more details.
 */
export interface FraudDetails {
    /**
     * IPv4 or IPv6-formatted IP address of the customer at the time of payment.
     */
    'customer_ip': string;
    /**
     * Customer\'s email address.  This field can be omitted if `email` is provided in `email` field inside `payment_details` of create payment request, or in the create payment session request. Otherwise, this field is required.
     */
    'customer_email': string;
    /**
     * An unique identifier of your customer. If your system has the concept of user accounts, then the ID of the current logged in user would be appropriate.
     */
    'customer_id'?: string;
    /**
     * Customer\'s current language setting.
     */
    'browser_language'?: string;
    /**
     * Browser\'s [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) string.
     */
    'browser_user_agent'?: string;
    /**
     * A unique identifier for the current browser session. We expect this to behave similarly to the lifetime of [window.sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) in a web browsing context.
     */
    'browser_session_id'?: string;
    /**
     * Customer\'s phone number.
     */
    'phone'?: string;
}

