/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LineItem
 */
export interface LineItem {
    /**
     * Amount greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
     * @type {number}
     * @memberof LineItem
     */
    'amount'?: number;
    /**
     * Display name or description of the product or service.
     * @type {string}
     * @memberof LineItem
     */
    'description'?: string;
    /**
     * The default value is 1 if none is given.
     * @type {number}
     * @memberof LineItem
     */
    'quantity'?: number;
    /**
     * URL to an image representing this line item, shown on the session page.
     * @type {string}
     * @memberof LineItem
     */
    'image'?: string;
    /**
     * Merchant\'s internal product or SKU identifier.
     * @type {string}
     * @memberof LineItem
     */
    'external_product_num'?: string;
}

