/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ErroredField } from './errored-field';
// May contain unused imports in some cases
// @ts-ignore
import type { Field } from './field';
// May contain unused imports in some cases
// @ts-ignore
import type { LiveApplication } from './live-application';
// May contain unused imports in some cases
// @ts-ignore
import type { LiveApplicationStatus } from './live-application-status';
// May contain unused imports in some cases
// @ts-ignore
import type { SubmittedField } from './submitted-field';

/**
 * @type LiveApplicationWithSubmittedFields
 * @export
 */
export type LiveApplicationWithSubmittedFields = LiveApplication;


