/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { SettlementFrequency } from './settlement-frequency';

/**
 * 
 * @export
 * @interface MerchantBalance
 */
export interface MerchantBalance {
    /**
     * 
     * @type {Currency}
     * @memberof MerchantBalance
     */
    'currency': Currency;
    /**
     * 
     * @type {SettlementFrequency}
     * @memberof MerchantBalance
     */
    'frequency': SettlementFrequency;
    /**
     * Amount greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
     * @type {number}
     * @memberof MerchantBalance
     */
    'settlement_minimum_amount': number;
}



