/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MerchantSubmissionStatus {
    /**
     * Identifier of the merchant whose submission status is being reported.
     */
    'merchant_id': string;
    /**
     * Current status of the merchant\'s live application submission.
     */
    'status': string;
}

