/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Payment } from './payment';
// May contain unused imports in some cases
// @ts-ignore
import type { SessionStatus } from './session-status';
// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionCustomer } from './subscription-customer';

export interface PaySessionResponse {
    /**
     * URL to redirect the customer to after submitting payment details, or null if no redirect is required.
     */
    'redirect_url': string | null;
    'status': SessionStatus;
    'payment'?: Payment;
    /**
     * URL for the payment app. Only present for offsite payments with a QR/app URL.
     */
    'app_url'?: string;
    'customer'?: SubscriptionCustomer;
}



