/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentDetailsKonbini
 */
export interface PaymentDetailsKonbini {
    /**
     * Payment method type.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'type': PaymentDetailsKonbiniTypeEnum;
    /**
     * Specify the name of convenience store user will make payment from.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'store': PaymentDetailsKonbiniStoreEnum;
    /**
     * Customer\'s email address. Will be used for fraud prevention, payment instruction, and payment receipt.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'email': string;
    /**
     * Customer\'s phone number
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'phone'?: string;
    /**
     * Family name of the customer. It will appear on the Konbini payment receipt.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'family_name'?: string;
    /**
     * Given name of the customer. It will appear on the Konbini payment receipt.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'given_name'?: string;
    /**
     * Specify how many days before the payment expires.  If this value is omitted, the default expiry day shown in the merchant dashboard will be used.
     * @type {number}
     * @memberof PaymentDetailsKonbini
     */
    'expiry_days'?: number;
    /**
     * Shipping address name. This is the recipient\'s name.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'shipping_address_name'?: string;
    /**
     * Shipping address line 1.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'shipping_address_line1'?: string;
    /**
     * Shipping address line 2.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'shipping_address_line2'?: string;
    /**
     * Shipping address city.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'shipping_address_city'?: string;
    /**
     * Shipping address state.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'shipping_address_state'?: string;
    /**
     * Shipping address ZIP code.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'shipping_address_zip'?: string;
    /**
     * Shipping address country.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'shipping_address_country'?: string;
    /**
     * Billing address name. This is the paying customer\'s name.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'billing_address_name'?: string;
    /**
     * Billing address line 1.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'billing_address_line1'?: string;
    /**
     * Billing address line 2.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'billing_address_line2'?: string;
    /**
     * Billing address city.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'billing_address_city'?: string;
    /**
     * Billing address state.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'billing_address_state'?: string;
    /**
     * Billing address ZIP code.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'billing_address_zip'?: string;
    /**
     * Billing address country.
     * @type {string}
     * @memberof PaymentDetailsKonbini
     */
    'billing_address_country'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum PaymentDetailsKonbiniTypeEnum {
    Konbini = 'konbini'
}
/**
    * @export
    * @enum {string}
    */
export enum PaymentDetailsKonbiniStoreEnum {
    SevenEleven = 'seven-eleven',
    Lawson = 'lawson',
    FamilyMart = 'family-mart',
    Ministop = 'ministop',
    DailyYamazaki = 'daily-yamazaki',
    Seicomart = 'seicomart'
}


