/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentDetailsPaidy
 */
export interface PaymentDetailsPaidy {
    /**
     * Payment method type.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'type': PaymentDetailsPaidyTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof PaymentDetailsPaidy
     */
    'customer_age'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentDetailsPaidy
     */
    'customer_last_order_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentDetailsPaidy
     */
    'customer_last_order_at'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentDetailsPaidy
     */
    'customer_lifetime_value'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'customer_name': string;
    /**
     * 
     * @type {number}
     * @memberof PaymentDetailsPaidy
     */
    'customer_order_count'?: number;
    /**
     * Customer\'s email address. Will be used for fraud prevention and payment receipt.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'email'?: string;
    /**
     * Customer\'s phone number
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'external_customer_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'item_title'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'customer_name_kana'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentDetailsPaidy
     */
    'capture'?: boolean;
    /**
     * Shipping address name.  This is the recipient\'s name.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'shipping_address_name'?: string;
    /**
     * Shipping address line 1.  For Japanese addresses: building name, apartment number. Required for physical products.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'shipping_address_line1'?: string;
    /**
     * Shipping address line 2.  For Japanese addresses: district, land number, land number extension.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'shipping_address_line2'?: string;
    /**
     * Shipping address city.  Name of city, municipality, or village. Required for physical products.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'shipping_address_city'?: string;
    /**
     * Shipping address state / prefecture.  Required for physical products.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'shipping_address_state'?: string;
    /**
     * Shipping address ZIP code, in a 7-digit format (NNN-NNNN). Required for physical products.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'shipping_address_zip'?: string;
    /**
     * Shipping address country. Required for physical products.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'shipping_address_country'?: string;
    /**
     * Billing address name. This is the paying customer\'s name.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'billing_address_name'?: string;
    /**
     * Billing address line 1.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'billing_address_line1'?: string;
    /**
     * Billing address line 2.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'billing_address_line2'?: string;
    /**
     * Billing address city.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'billing_address_city'?: string;
    /**
     * Billing address state.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'billing_address_state'?: string;
    /**
     * Billing address ZIP code.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'billing_address_zip'?: string;
    /**
     * Billing address country.
     * @type {string}
     * @memberof PaymentDetailsPaidy
     */
    'billing_address_country'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum PaymentDetailsPaidyTypeEnum {
    Paidy = 'paidy'
}


