/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentMethodBrands } from './payment-method-brands';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentMethodInstallmentsInner } from './payment-method-installments-inner';

/**
 * 
 * @export
 * @interface PaymentMethod
 */
export interface PaymentMethod {
    /**
     * Machine-readable type slug for this payment method (e.g. \"credit_card\", \"konbini\").
     * @type {string}
     * @memberof PaymentMethod
     */
    'type': string;
    /**
     * Hashed identifier of the payment gateway processing this method.
     * @type {string}
     * @memberof PaymentMethod
     */
    'hashed_gateway'?: string;
    /**
     * Amount greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
     * @type {number}
     * @memberof PaymentMethod
     */
    'amount'?: number;
    /**
     * 
     * @type {Currency}
     * @memberof PaymentMethod
     */
    'currency'?: Currency;
    /**
     * Exchange rate applied when this payment method\'s currency differs from the session currency.
     * @type {number}
     * @memberof PaymentMethod
     */
    'exchange_rate'?: number;
    /**
     * Whether this payment method redirects the customer to an external site to complete payment.
     * @type {boolean}
     * @memberof PaymentMethod
     */
    'offsite'?: boolean;
    /**
     * Names of additional input fields required to complete payment with this method.
     * @type {Array<string>}
     * @memberof PaymentMethod
     */
    'additional_fields'?: Array<string>;
    /**
     * 
     * @type {PaymentMethodBrands}
     * @memberof PaymentMethod
     */
    'brands'?: PaymentMethodBrands;
    /**
     * Only for Konbini
     * @type {string}
     * @memberof PaymentMethod
     */
    'seven_eleven_merchant_number'?: string | null;
    /**
     * Only for Komoju Pay
     * @type {Array<PaymentMethodInstallmentsInner>}
     * @memberof PaymentMethod
     */
    'installments'?: Array<PaymentMethodInstallmentsInner>;
    /**
     * Only for Komoju Pay
     * @type {string}
     * @memberof PaymentMethod
     */
    'api_endpoint'?: string;
}



