/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentMethodInstallmentsInner
 */
export interface PaymentMethodInstallmentsInner {
    /**
     * Amount due for this installment, in the lowest denomination of the currency.
     * @type {number}
     * @memberof PaymentMethodInstallmentsInner
     */
    'amount': number;
    /**
     * Date when this installment payment is due.
     * @type {string}
     * @memberof PaymentMethodInstallmentsInner
     */
    'pay_at': string;
}

