/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentDetailsCreditCardTerminal
 */
export interface PaymentDetailsCreditCardTerminal {
    /**
     * Payment method type.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'type': PaymentDetailsCreditCardTerminalTypeEnum;
    /**
     * Credit card number.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'number': string;
    /**
     * Credit card expiration month.
     * @type {number}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'month'?: number;
    /**
     * Credit card expiration year.  If this value is less than 100, it will be treated as two digits year in the current century. E.g. If current year is `2024`, `99` means `2099`.
     * @type {number}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'year'?: number;
    /**
     * Specify the sequence number from the credit card terminal
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'sequence_number'?: string;
    /**
     * Specify the EMV data produced by the terminal.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'field55'?: string;
    /**
     * Specify the POS data code produced by the terminal.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'posDataCode'?: string;
    /**
     * Specify the data read from track 2 of the payment card.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'track2'?: string;
    /**
     * Specify whether this transaction is a EMV or magnetic stripe transaction.  - Use value \"1\" for EMV transaction. - Use value \"2\" for magnetic stripe transaction.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'flowType'?: string;
    /**
     * Shipping address name. This is the recipient\'s name.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'shipping_address_name'?: string;
    /**
     * Shipping address line 1.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'shipping_address_line1'?: string;
    /**
     * Shipping address line 2.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'shipping_address_line2'?: string;
    /**
     * Shipping address city.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'shipping_address_city'?: string;
    /**
     * Shipping address state.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'shipping_address_state'?: string;
    /**
     * Shipping address ZIP code.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'shipping_address_zip'?: string;
    /**
     * Shipping address country.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'shipping_address_country'?: string;
    /**
     * Billing address name. This is the paying customer\'s name.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'billing_address_name'?: string;
    /**
     * Billing address line 1.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'billing_address_line1'?: string;
    /**
     * Billing address line 2.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'billing_address_line2'?: string;
    /**
     * Billing address city.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'billing_address_city'?: string;
    /**
     * Billing address state.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'billing_address_state'?: string;
    /**
     * Billing address ZIP code.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'billing_address_zip'?: string;
    /**
     * Billing address country.
     * @type {string}
     * @memberof PaymentDetailsCreditCardTerminal
     */
    'billing_address_country'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum PaymentDetailsCreditCardTerminalTypeEnum {
    CreditCardTerminal = 'credit_card_terminal'
}


