/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaymentMethodStatus } from './payment-method-status';

/**
 * 
 * @export
 * @interface PaymentMethodsList
 */
export interface PaymentMethodsList {
    /**
     * Array of payment methods that have been submitted for review, with their statuses.
     * @type {Array<PaymentMethodStatus>}
     * @memberof PaymentMethodsList
     */
    'submitted_payment_methods': Array<PaymentMethodStatus>;
    /**
     * Array of payment method type slugs that have not yet been submitted for review.
     * @type {Array<string>}
     * @memberof PaymentMethodsList
     */
    'unsubmitted_payment_methods': Array<string>;
}

