/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Installments } from './installments';
// May contain unused imports in some cases
// @ts-ignore
import type { Intent } from './intent';

/**
 * 
 */
export interface PaymentDetailsCreditCard {
    /**
     * Payment method type.
     */
    'type': PaymentDetailsCreditCardTypeEnum;
    /**
     * Customer\'s email address. Will be used for fraud prevention and payment receipt.
     */
    'email'?: string;
    /**
     * Credit card number.
     */
    'number': string;
    /**
     * Credit card expiration month.
     */
    'month': number;
    /**
     * Credit card expiration year.  If this value is less than 100, it will be treated as two digits year in the current century. E.g. If current year is `2024`, `99` means `2099`.
     */
    'year': number;
    /**
     * Credit card verification value (Also known as CVV2 or CVC2).
     */
    'verification_value'?: string;
    /**
     * Full name of the customer.  This attribute takes precedence over `given_name` and `family_name`.
     */
    'name'?: string;
    /**
     * Given name of the customer.  **Note:** You should only set this attribute if you have separate fields for given name and family name. Otherwise, you should only set the full name via `name`.
     */
    'given_name'?: string;
    /**
     * Family name of the customer.  **Note:** You should only set this attribute if you have separate fields for given name and family name. Otherwise, you should only set the full name via `name`.
     */
    'family_name'?: string;
    /**
     * If the payment is not immediately captured, specify how many days before the payment expires.  If this value is omitted, the default expiry day shown in the merchant dashboard will be used.
     */
    'expiry_days'?: number;
    'intent'?: Intent;
    /**
     * Specify the initiator of this payment.  Specifying this attribute can increase authorization credit card payments authorization rates, especially when using a stored card.  You can set this value to `customer` when the payment is being made for one-time goods or service purchase, or `merchant` for recurring subscription or installment payments.
     */
    'initiator'?: PaymentDetailsCreditCardInitiatorEnum;
    /**
     * Specify whether this payment is the first (`first`) or a subsequent payment in a series (`used`).  Specifying this attribute can increase authorization credit card payments authorization rates, especially when using a stored card.
     */
    'usage'?: PaymentDetailsCreditCardUsageEnum;
    /**
     * Specify a scheme reference value, which is used to track the chain of multiple related payments.  This value can be subscription number for a recurring subscription payments, or installment agreement number for installment payments.  Specifying this attribute can increase authorization credit card payments authorization rates, especially when using a stored card.
     */
    'scheme_reference'?: string;
    'installments'?: Installments;
    /**
     * Shipping address name. This is the recipient\'s name.
     */
    'shipping_address_name'?: string;
    /**
     * Shipping address line 1.
     */
    'shipping_address_line1'?: string;
    /**
     * Shipping address line 2.
     */
    'shipping_address_line2'?: string;
    /**
     * Shipping address city.
     */
    'shipping_address_city'?: string;
    /**
     * Shipping address state.
     */
    'shipping_address_state'?: string;
    /**
     * Shipping address ZIP code.
     */
    'shipping_address_zip'?: string;
    /**
     * Shipping address country.
     */
    'shipping_address_country'?: string;
    /**
     * Billing address name. This is the paying customer\'s name.
     */
    'billing_address_name'?: string;
    /**
     * Billing address line 1.
     */
    'billing_address_line1'?: string;
    /**
     * Billing address line 2.
     */
    'billing_address_line2'?: string;
    /**
     * Billing address city.
     */
    'billing_address_city'?: string;
    /**
     * Billing address state.
     */
    'billing_address_state'?: string;
    /**
     * Billing address ZIP code.
     */
    'billing_address_zip'?: string;
    /**
     * Billing address country.
     */
    'billing_address_country'?: string;
}

export enum PaymentDetailsCreditCardTypeEnum {
    CreditCard = 'credit_card'
}
export enum PaymentDetailsCreditCardInitiatorEnum {
    Merchant = 'merchant',
    Customer = 'customer'
}
export enum PaymentDetailsCreditCardUsageEnum {
    First = 'first',
    Used = 'used'
}


