/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { Intent } from './intent';
// May contain unused imports in some cases
// @ts-ignore
import type { PlatformDetails } from './platform-details';
// May contain unused imports in some cases
// @ts-ignore
import type { StatementDescriptor } from './statement-descriptor';

export interface PaymentDataRequest {
    /**
     * Whether to capture the payment automatically on completion, or hold it for manual capture later.
     */
    'capture'?: PaymentDataRequestCaptureEnum;
    /**
     * Amount greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
     */
    'amount'?: number;
    'currency'?: Currency;
    /**
     * Merchant-assigned order reference number to associate with the payment.
     */
    'external_order_num'?: string;
    /**
     * Customer\'s full name.
     */
    'name'?: string;
    /**
     * Customer\'s full name in katakana.
     */
    'name_kana'?: string;
    /**
     * Merchant Category Code to use for this payment.
     */
    'mcc'?: string;
    'intent'?: Intent;
    'statement_descriptor'?: StatementDescriptor;
    'platform_details'?: PlatformDetails;
    'billing_address'?: Address;
    'shipping_address'?: Address;
}

export enum PaymentDataRequestCaptureEnum {
    Auto = 'auto',
    Manual = 'manual'
}


