/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * @type PaymentDetailsCreditCardKoreaSocialId
 * This attribute differs whether the payment card is personal or corporate card.  - For personal card, you should specify customer\'s date of birth. - For corporate card, you should specify payment card\'s corporate number.
 * @export
 */
export type PaymentDetailsCreditCardKoreaSocialId = string;


