/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Submerchant } from './submerchant';

/**
 * 
 * @export
 * @interface PlatformDetails
 */
export interface PlatformDetails {
    /**
     * Array of submerchant split configurations for this platform payment.
     * @type {Array<Submerchant>}
     * @memberof PlatformDetails
     */
    'submerchants': Array<Submerchant>;
    /**
     * A unique 25-character alphanumeric resource identifier.
     * @type {string}
     * @memberof PlatformDetails
     */
    'processing_merchant_id'?: string;
}

