/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PrepaidCards
 */
export interface PrepaidCards {
    /**
     * Last four digits of the prepaid card number.
     * @type {string}
     * @memberof PrepaidCards
     */
    'last_four_digits'?: string;
    /**
     * Points or remaining balance on this prepaid card.
     * @type {number}
     * @memberof PrepaidCards
     */
    'points'?: number;
}

