/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { PlatformDetails } from './platform-details';

/**
 * 
 * @export
 * @interface Refund
 */
export interface Refund {
    /**
     * A unique 25-character alphanumeric refund identifier.
     * @type {string}
     * @memberof Refund
     */
    'id': string;
    /**
     * Resource name. Will always be `refund`.
     * @type {string}
     * @memberof Refund
     */
    'resource': RefundResourceEnum;
    /**
     * The refund amount with tax included, greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
     * @type {number}
     * @memberof Refund
     */
    'amount': number;
    /**
     * 
     * @type {Currency}
     * @memberof Refund
     */
    'currency': Currency;
    /**
     * A unique 25-character alphanumeric payment identifier.
     * @type {string}
     * @memberof Refund
     */
    'payment': string;
    /**
     * Description of the refund.
     * @type {string}
     * @memberof Refund
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof Refund
     */
    'created_at': string;
    /**
     * Denotes if this refund was created due to a chargeback.
     * @type {boolean}
     * @memberof Refund
     */
    'chargeback': boolean;
    /**
     * 
     * @type {string}
     * @memberof Refund
     */
    'refund_type'?: string;
    /**
     * 
     * @type {PlatformDetails}
     * @memberof Refund
     */
    'platform_details'?: PlatformDetails;
}

/**
    * @export
    * @enum {string}
    */
export enum RefundResourceEnum {
    Refund = 'refund'
}


