/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PlatformDetails } from './platform-details';
// May contain unused imports in some cases
// @ts-ignore
import type { RefundRequestStatus } from './refund-request-status';

export interface RefundRequest {
    /**
     * A unique 25-character alphanumeric refund request identifier.
     */
    'id': string;
    /**
     * A unique 25-character alphanumeric payment identifier.
     */
    'payment': string;
    /**
     * Customer\'s name in half-width katakana characters.
     */
    'customer_name': string;
    /**
     * The name of the bank that customer would like money to be deposited to.
     */
    'bank_name': string;
    /**
     * 4-digit bank code. May be `null` if it\'s not given.
     */
    'bank_code': string;
    /**
     * The name of the branch.
     */
    'branch_name': string;
    /**
     * 3-digit branch number.
     */
    'branch_number': string;
    /**
     * 7-digit account number.
     */
    'account_number': string;
    /**
     * Optional description or reason for this refund request.
     */
    'description'?: string;
    'status': RefundRequestStatus;
    /**
     * Timestamp when the refund request was created.
     */
    'created_at': string;
    'platform_details'?: PlatformDetails;
}



