/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResponsePaymentDetailsEpospay
 */
export interface ResponsePaymentDetailsEpospay {
    /**
     * Payment method type.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'type': ResponsePaymentDetailsEpospayTypeEnum;
    /**
     * Customer\'s email address. Will be used for fraud prevention and payment receipt.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'email': string;
    /**
     * When using test mode.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'offsite_fake_new_path'?: string;
    /**
     * URL for the customer to complete the EPOS payment offsite.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'offsite_url'?: string;
    /**
     * Merchant identifier used in the EPOS payment request.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'merchant_id'?: string;
    /**
     * Shop identifier used in the EPOS payment request.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'shop_id'?: string;
    /**
     * Deal identifier for this EPOS transaction.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'deal_id'?: string;
    /**
     * Authentication token for the EPOS payment.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'token'?: string;
    /**
     * Product list data for the EPOS payment.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'prd_list'?: string;
    /**
     * Payment amount in the lowest denomination of the currency.
     * @type {number}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'amount'?: number;
    /**
     * Customer identifier in the EPOS system.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'customer_id'?: string;
    /**
     * URL to redirect the customer to after completing the EPOS payment.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'return_url'?: string;
    /**
     * Shipping address name. This is the recipient\'s name.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'shipping_address_name'?: string;
    /**
     * Shipping address line 1.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'shipping_address_line1'?: string;
    /**
     * Shipping address line 2.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'shipping_address_line2'?: string;
    /**
     * Shipping address city.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'shipping_address_city'?: string;
    /**
     * Shipping address state.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'shipping_address_state'?: string;
    /**
     * Shipping address ZIP code.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'shipping_address_zip'?: string;
    /**
     * Shipping address country.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'shipping_address_country'?: string;
    /**
     * Billing address name. This is the paying customer\'s name.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'billing_address_name'?: string;
    /**
     * Billing address line 1.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'billing_address_line1'?: string;
    /**
     * Billing address line 2.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'billing_address_line2'?: string;
    /**
     * Billing address city.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'billing_address_city'?: string;
    /**
     * Billing address state.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'billing_address_state'?: string;
    /**
     * Billing address ZIP code.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'billing_address_zip'?: string;
    /**
     * Billing address country.
     * @type {string}
     * @memberof ResponsePaymentDetailsEpospay
     */
    'billing_address_country'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ResponsePaymentDetailsEpospayTypeEnum {
    Epospay = 'epospay'
}


