/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResponsePaymentDetailsKonbini
 */
export interface ResponsePaymentDetailsKonbini {
    /**
     * Payment method type.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'type': ResponsePaymentDetailsKonbiniTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'store': ResponsePaymentDetailsKonbiniStoreEnum;
    /**
     * Customer\'s email address. Will be used for fraud prevention, payment instruction, and payment receipt.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'email': string;
    /**
     * Confirmation code for the konbini payment slip.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'confirmation_code'?: string | null;
    /**
     * Receipt number for the konbini payment.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'receipt'?: string | null;
    /**
     * URL with payment instructions for the customer.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'instructions_url'?: string;
    /**
     * Shipping address name. This is the recipient\'s name.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'shipping_address_name'?: string;
    /**
     * Shipping address line 1.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'shipping_address_line1'?: string;
    /**
     * Shipping address line 2.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'shipping_address_line2'?: string;
    /**
     * Shipping address city.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'shipping_address_city'?: string;
    /**
     * Shipping address state.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'shipping_address_state'?: string;
    /**
     * Shipping address ZIP code.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'shipping_address_zip'?: string;
    /**
     * Shipping address country.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'shipping_address_country'?: string;
    /**
     * Billing address name. This is the paying customer\'s name.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'billing_address_name'?: string;
    /**
     * Billing address line 1.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'billing_address_line1'?: string;
    /**
     * Billing address line 2.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'billing_address_line2'?: string;
    /**
     * Billing address city.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'billing_address_city'?: string;
    /**
     * Billing address state.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'billing_address_state'?: string;
    /**
     * Billing address ZIP code.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'billing_address_zip'?: string;
    /**
     * Billing address country.
     * @type {string}
     * @memberof ResponsePaymentDetailsKonbini
     */
    'billing_address_country'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ResponsePaymentDetailsKonbiniTypeEnum {
    Konbini = 'konbini'
}
/**
    * @export
    * @enum {string}
    */
export enum ResponsePaymentDetailsKonbiniStoreEnum {
    SevenEleven = 'seven-eleven',
    Lawson = 'lawson',
    FamilyMart = 'family-mart',
    Ministop = 'ministop',
    DailyYamazaki = 'daily-yamazaki',
    Seicomart = 'seicomart'
}


