/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 */
export interface ResponsePaymentDetailsBankTransfer {
    /**
     * Payment method type.
     */
    'type': ResponsePaymentDetailsBankTransferTypeEnum;
    /**
     * Customer\'s email address. Will be used for fraud prevention, payment instruction, and payment receipt.
     */
    'email': string;
    /**
     * Order identifier for this bank transfer.
     */
    'order_id'?: string;
    /**
     * Name of the bank to transfer funds to.
     */
    'bank_name'?: string;
    /**
     * Name of the bank branch.
     */
    'account_branch_name'?: string;
    /**
     * Bank account number to transfer funds to.
     */
    'account_number'?: string;
    /**
     * Type of bank account.
     */
    'account_type'?: string;
    /**
     * Name of the bank account holder.
     */
    'account_name'?: string;
    /**
     * URL with payment instructions for the customer.
     */
    'instructions_url'?: string;
    /**
     * Deadline by which the bank transfer must be completed.
     */
    'payment_deadline'?: string;
    /**
     * Shipping address name. This is the recipient\'s name.
     */
    'shipping_address_name'?: string;
    /**
     * Shipping address line 1.
     */
    'shipping_address_line1'?: string;
    /**
     * Shipping address line 2.
     */
    'shipping_address_line2'?: string;
    /**
     * Shipping address city.
     */
    'shipping_address_city'?: string;
    /**
     * Shipping address state.
     */
    'shipping_address_state'?: string;
    /**
     * Shipping address ZIP code.
     */
    'shipping_address_zip'?: string;
    /**
     * Shipping address country.
     */
    'shipping_address_country'?: string;
    /**
     * Billing address name. This is the paying customer\'s name.
     */
    'billing_address_name'?: string;
    /**
     * Billing address line 1.
     */
    'billing_address_line1'?: string;
    /**
     * Billing address line 2.
     */
    'billing_address_line2'?: string;
    /**
     * Billing address city.
     */
    'billing_address_city'?: string;
    /**
     * Billing address state.
     */
    'billing_address_state'?: string;
    /**
     * Billing address ZIP code.
     */
    'billing_address_zip'?: string;
    /**
     * Billing address country.
     */
    'billing_address_country'?: string;
}

export enum ResponsePaymentDetailsBankTransferTypeEnum {
    BankTransfer = 'bank_transfer'
}


