/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResponsePaymentDetailsCreditCardTerminal
 */
export interface ResponsePaymentDetailsCreditCardTerminal {
    /**
     * Payment method type.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'type': ResponsePaymentDetailsCreditCardTerminalTypeEnum;
    /**
     * Card brand (e.g. \"visa\", \"mastercard\").
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'brand'?: string;
    /**
     * Last four digits of the card used.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'last_four_digits'?: string;
    /**
     * Credit card expiration month.
     * @type {number}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'month'?: number;
    /**
     * Credit card expiration year.  If this value is less than 100, it will be treated as two digits year in the current century. E.g. If current year is `2024`, `99` means `2099`.
     * @type {number}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'year'?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'field55'?: string;
    /**
     * Status code returned by the Cardnet network.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'cardnet_status'?: string;
    /**
     * Approval number returned by the card network.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'approval_number'?: string;
    /**
     * Shipping address name. This is the recipient\'s name.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'shipping_address_name'?: string;
    /**
     * Shipping address line 1.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'shipping_address_line1'?: string;
    /**
     * Shipping address line 2.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'shipping_address_line2'?: string;
    /**
     * Shipping address city.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'shipping_address_city'?: string;
    /**
     * Shipping address state.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'shipping_address_state'?: string;
    /**
     * Shipping address ZIP code.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'shipping_address_zip'?: string;
    /**
     * Shipping address country.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'shipping_address_country'?: string;
    /**
     * Billing address name. This is the paying customer\'s name.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'billing_address_name'?: string;
    /**
     * Billing address line 1.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'billing_address_line1'?: string;
    /**
     * Billing address line 2.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'billing_address_line2'?: string;
    /**
     * Billing address city.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'billing_address_city'?: string;
    /**
     * Billing address state.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'billing_address_state'?: string;
    /**
     * Billing address ZIP code.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'billing_address_zip'?: string;
    /**
     * Billing address country.
     * @type {string}
     * @memberof ResponsePaymentDetailsCreditCardTerminal
     */
    'billing_address_country'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ResponsePaymentDetailsCreditCardTerminalTypeEnum {
    CreditCardTerminal = 'credit_card_terminal'
}


