/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResponsePaymentDetailsPayEasy
 */
export interface ResponsePaymentDetailsPayEasy {
    /**
     * Payment method type.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'type': ResponsePaymentDetailsPayEasyTypeEnum;
    /**
     * Customer\'s email address. Will be used for fraud prevention, payment instruction, and payment receipt.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'email': string;
    /**
     * Bank identifier for the Pay-easy payment.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'bank_id'?: string;
    /**
     * Customer identifier for the Pay-easy payment.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'customer_id'?: string;
    /**
     * Confirmation ID for the Pay-easy payment.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'confirmation_id'?: string;
    /**
     * URL with payment instructions for the customer.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'instructions_url'?: string;
    /**
     * URL where the customer can complete the Pay-easy payment online.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'payment_url'?: string;
    /**
     * CVS code for convenience store payment.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'cvs_code'?: string | null;
    /**
     * Shipping address name. This is the recipient\'s name.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'shipping_address_name'?: string;
    /**
     * Shipping address line 1.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'shipping_address_line1'?: string;
    /**
     * Shipping address line 2.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'shipping_address_line2'?: string;
    /**
     * Shipping address city.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'shipping_address_city'?: string;
    /**
     * Shipping address state.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'shipping_address_state'?: string;
    /**
     * Shipping address ZIP code.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'shipping_address_zip'?: string;
    /**
     * Shipping address country.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'shipping_address_country'?: string;
    /**
     * Billing address name. This is the paying customer\'s name.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'billing_address_name'?: string;
    /**
     * Billing address line 1.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'billing_address_line1'?: string;
    /**
     * Billing address line 2.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'billing_address_line2'?: string;
    /**
     * Billing address city.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'billing_address_city'?: string;
    /**
     * Billing address state.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'billing_address_state'?: string;
    /**
     * Billing address ZIP code.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'billing_address_zip'?: string;
    /**
     * Billing address country.
     * @type {string}
     * @memberof ResponsePaymentDetailsPayEasy
     */
    'billing_address_country'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ResponsePaymentDetailsPayEasyTypeEnum {
    PayEasy = 'pay_easy'
}


