/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 */
export interface ResponsePaymentDetailsWechatpay {
    /**
     * Payment method type.
     */
    'type': ResponsePaymentDetailsWechatpayTypeEnum;
    /**
     * Customer\'s email address. Will be used for fraud prevention and payment receipt.
     */
    'email': string;
    /**
     * URL to the QR code image for the WeChat Pay payment.
     */
    'qr_code_url'?: string;
    /**
     * Mobile web URL for the WeChat Pay payment flow.
     */
    'mweb_url'?: string;
    /**
     * WeChat Pay trade type: NATIVE for QR code, MWEB for mobile web.
     */
    'trade_type'?: ResponsePaymentDetailsWechatpayTradeTypeEnum;
    /**
     * URL to redirect the customer to for completing the WeChat Pay payment.
     */
    'redirect_url'?: string;
    /**
     * Shipping address name. This is the recipient\'s name.
     */
    'shipping_address_name'?: string;
    /**
     * Shipping address line 1.
     */
    'shipping_address_line1'?: string;
    /**
     * Shipping address line 2.
     */
    'shipping_address_line2'?: string;
    /**
     * Shipping address city.
     */
    'shipping_address_city'?: string;
    /**
     * Shipping address state.
     */
    'shipping_address_state'?: string;
    /**
     * Shipping address ZIP code.
     */
    'shipping_address_zip'?: string;
    /**
     * Shipping address country.
     */
    'shipping_address_country'?: string;
    /**
     * Billing address name. This is the paying customer\'s name.
     */
    'billing_address_name'?: string;
    /**
     * Billing address line 1.
     */
    'billing_address_line1'?: string;
    /**
     * Billing address line 2.
     */
    'billing_address_line2'?: string;
    /**
     * Billing address city.
     */
    'billing_address_city'?: string;
    /**
     * Billing address state.
     */
    'billing_address_state'?: string;
    /**
     * Billing address ZIP code.
     */
    'billing_address_zip'?: string;
    /**
     * Billing address country.
     */
    'billing_address_country'?: string;
}

export enum ResponsePaymentDetailsWechatpayTypeEnum {
    Wechatpay = 'wechatpay'
}
export enum ResponsePaymentDetailsWechatpayTradeTypeEnum {
    Native = 'NATIVE',
    Mweb = 'MWEB'
}


