/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 */
export interface ResponsePaymentDetailsNaverpay {
    /**
     * Payment method type.
     */
    'type': ResponsePaymentDetailsNaverpayTypeEnum;
    /**
     * Customer\'s email address. Will be used for fraud prevention and payment receipt.
     */
    'email': string;
    /**
     * Callback URL used in the Naver Pay payment flow.
     */
    'callback_url'?: string;
    /**
     * Environment mode for the Naver Pay integration.
     */
    'mode'?: ResponsePaymentDetailsNaverpayModeEnum;
    /**
     * Whether the payment uses a redirect flow.
     */
    'redirect'?: boolean;
    /**
     * When using test mode.
     */
    'offsite_fake_new_path'?: string;
    /**
     * Naver Pay client ID for this merchant.
     */
    'client_id'?: string;
    /**
     * Whether this payment is for digital content only.
     */
    'digital_content_only'?: boolean;
    /**
     * Shipping address name. This is the recipient\'s name.
     */
    'shipping_address_name'?: string;
    /**
     * Shipping address line 1.
     */
    'shipping_address_line1'?: string;
    /**
     * Shipping address line 2.
     */
    'shipping_address_line2'?: string;
    /**
     * Shipping address city.
     */
    'shipping_address_city'?: string;
    /**
     * Shipping address state.
     */
    'shipping_address_state'?: string;
    /**
     * Shipping address ZIP code.
     */
    'shipping_address_zip'?: string;
    /**
     * Shipping address country.
     */
    'shipping_address_country'?: string;
    /**
     * Billing address name. This is the paying customer\'s name.
     */
    'billing_address_name'?: string;
    /**
     * Billing address line 1.
     */
    'billing_address_line1'?: string;
    /**
     * Billing address line 2.
     */
    'billing_address_line2'?: string;
    /**
     * Billing address city.
     */
    'billing_address_city'?: string;
    /**
     * Billing address state.
     */
    'billing_address_state'?: string;
    /**
     * Billing address ZIP code.
     */
    'billing_address_zip'?: string;
    /**
     * Billing address country.
     */
    'billing_address_country'?: string;
}

export enum ResponsePaymentDetailsNaverpayTypeEnum {
    Naverpay = 'naverpay'
}
export enum ResponsePaymentDetailsNaverpayModeEnum {
    Production = 'production',
    Development = 'development'
}


