/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Installments } from './installments';

/**
 * 
 */
export interface ResponsePaymentDetailsCreditCard {
    /**
     * Payment method type.
     */
    'type': ResponsePaymentDetailsCreditCardTypeEnum;
    /**
     * Card brand (e.g. \"visa\", \"mastercard\", \"jcb\").
     */
    'brand': string;
    /**
     * Last four digits of the card number.
     */
    'last_four_digits': string;
    /**
     * Credit card expiration month.
     */
    'month': number;
    /**
     * Credit card expiration year.  If this value is less than 100, it will be treated as two digits year in the current century. E.g. If current year is `2024`, `99` means `2099`.
     */
    'year': number;
    /**
     * Customer\'s email address. Will be used for fraud prevention and payment receipt.
     */
    'email': string;
    'verification_value'?: ResponsePaymentDetailsCreditCardVerificationValueEnum;
    /**
     * Full name of the customer.  This attribute takes precedence over `given_name` and `family_name`.
     */
    'name'?: string;
    /**
     * Given name of the customer.
     */
    'given_name'?: string;
    /**
     * Family name of the customer.
     */
    'family_name'?: string;
    'expiry_days'?: number;
    'intent'?: ResponsePaymentDetailsCreditCardIntentEnum;
    'initiator'?: ResponsePaymentDetailsCreditCardInitiatorEnum;
    'usage'?: ResponsePaymentDetailsCreditCardUsageEnum;
    'scheme_reference'?: string;
    'installments'?: Installments;
    /**
     * Shipping address name. This is the recipient\'s name.
     */
    'shipping_address_name'?: string;
    /**
     * Shipping address line 1.
     */
    'shipping_address_line1'?: string;
    /**
     * Shipping address line 2.
     */
    'shipping_address_line2'?: string;
    /**
     * Shipping address city.
     */
    'shipping_address_city'?: string;
    /**
     * Shipping address state.
     */
    'shipping_address_state'?: string;
    /**
     * Shipping address ZIP code.
     */
    'shipping_address_zip'?: string;
    /**
     * Shipping address country.
     */
    'shipping_address_country'?: string;
    /**
     * Billing address name. This is the paying customer\'s name.
     */
    'billing_address_name'?: string;
    /**
     * Billing address line 1.
     */
    'billing_address_line1'?: string;
    /**
     * Billing address line 2.
     */
    'billing_address_line2'?: string;
    /**
     * Billing address city.
     */
    'billing_address_city'?: string;
    /**
     * Billing address state.
     */
    'billing_address_state'?: string;
    /**
     * Billing address ZIP code.
     */
    'billing_address_zip'?: string;
    /**
     * Billing address country.
     */
    'billing_address_country'?: string;
}

export enum ResponsePaymentDetailsCreditCardTypeEnum {
    CreditCard = 'credit_card'
}
export enum ResponsePaymentDetailsCreditCardVerificationValueEnum {
    Approved = 'Approved',
    Invalid = 'Invalid',
    NotChecked = 'Not Checked',
    NotSupplied = 'Not Supplied'
}
export enum ResponsePaymentDetailsCreditCardIntentEnum {
    OneTime = 'one_time',
    CardOnFile = 'card_on_file',
    Subscription = 'subscription',
    Installment = 'installment'
}
export enum ResponsePaymentDetailsCreditCardInitiatorEnum {
    Merchant = 'merchant',
    Customer = 'customer'
}
export enum ResponsePaymentDetailsCreditCardUsageEnum {
    First = 'first',
    Used = 'used'
}


