/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResponsePaymentDetailsSoftbank
 */
export interface ResponsePaymentDetailsSoftbank {
    /**
     * Payment method type.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'type': ResponsePaymentDetailsSoftbankTypeEnum;
    /**
     * Customer\'s email address. Will be used for fraud prevention and payment receipt.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'email': string;
    /**
     * URL to redirect the customer to for completing the SoftBank payment.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'redirect_url'?: string;
    /**
     * Shipping address name. This is the recipient\'s name.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'shipping_address_name'?: string;
    /**
     * Shipping address line 1.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'shipping_address_line1'?: string;
    /**
     * Shipping address line 2.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'shipping_address_line2'?: string;
    /**
     * Shipping address city.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'shipping_address_city'?: string;
    /**
     * Shipping address state.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'shipping_address_state'?: string;
    /**
     * Shipping address ZIP code.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'shipping_address_zip'?: string;
    /**
     * Shipping address country.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'shipping_address_country'?: string;
    /**
     * Billing address name. This is the paying customer\'s name.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'billing_address_name'?: string;
    /**
     * Billing address line 1.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'billing_address_line1'?: string;
    /**
     * Billing address line 2.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'billing_address_line2'?: string;
    /**
     * Billing address city.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'billing_address_city'?: string;
    /**
     * Billing address state.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'billing_address_state'?: string;
    /**
     * Billing address ZIP code.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'billing_address_zip'?: string;
    /**
     * Billing address country.
     * @type {string}
     * @memberof ResponsePaymentDetailsSoftbank
     */
    'billing_address_country'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ResponsePaymentDetailsSoftbankTypeEnum {
    Softbank = 'softbank'
}


