/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 3DS Server account details. Only present when set on the SecureToken.
 */
export interface SecureTokenThreeDSecureAccount {
    /**
     * Acquirer Merchant ID, or null if not configured.
     */
    'acquirer_mid': string | null;
    /**
     * Acquirer BIN, or null if not configured.
     */
    'acquirer_bin': string | null;
}

