/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';

export interface SerializedSubmerchantExpirySettingsInner {
    /**
     * Human-readable name of the payment method this expiry setting applies to.
     */
    'name': string;
    /**
     * Machine-readable slug identifying the payment method.
     */
    'slug': string;
    'currency': Currency;
    /**
     * Amount greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
     */
    'expiry_days': number;
    /**
     * Amount greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
     */
    'default_expiry_days': number;
}



