/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Specifies what to do with the payment details. Can create a payment, or a customer resource.
 */

export enum SessionMode {
    Payment = 'payment',
    Customer = 'customer',
    CustomerPayment = 'customer_payment'
}



