/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SettlementDownload
 */
export interface SettlementDownload {
    /**
     * URL to download this settlement in CSV format, or null if unavailable.
     * @type {string}
     * @memberof SettlementDownload
     */
    'csv': string | null;
    /**
     * URL to download this settlement in XLS format, or null if unavailable.
     * @type {string}
     * @memberof SettlementDownload
     */
    'xls': string | null;
}

