/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SharedDetailsMisc {
    /**
     * Amount in the lowest denomination of the currency (e.g. cents for USD).
     */
    'clearings_total_cents': number;
    /**
     * Amount in the lowest denomination of the currency (e.g. cents for USD).
     */
    'komoju_card_discount_total_cents': number;
    /**
     * Amount in the lowest denomination of the currency (e.g. cents for USD).
     */
    'chargeback_fixed_fee_total_cents': number;
    /**
     * Amount in the lowest denomination of the currency (e.g. cents for USD).
     */
    'other_fee_adjustments_total_cents': number;
    /**
     * Amount in the lowest denomination of the currency (e.g. cents for USD).
     */
    'total_cents': number;
}

