/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SharedDetailsCorrections } from './shared-details-corrections';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedDetailsDisbursements } from './shared-details-disbursements';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedDetailsMisc } from './shared-details-misc';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedDetailsPayments } from './shared-details-payments';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedDetailsPlatformModel } from './shared-details-platform-model';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedDetailsRefunds } from './shared-details-refunds';

export interface SharedDetails {
    'payments': SharedDetailsPayments;
    'refunds': SharedDetailsRefunds;
    'platform_model'?: SharedDetailsPlatformModel;
    'corrections': SharedDetailsCorrections;
    'komoju_card_charges': SharedDetailsCorrections;
    'disbursements': SharedDetailsDisbursements;
    'misc': SharedDetailsMisc;
}

