/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SimulateLiveApplicationPaymentMethodStatusRequest
 */
export interface SimulateLiveApplicationPaymentMethodStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof SimulateLiveApplicationPaymentMethodStatusRequest
     */
    'status'?: SimulateLiveApplicationPaymentMethodStatusRequestStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SimulateLiveApplicationPaymentMethodStatusRequestStatusEnum {
    Accepted = 'accepted',
    Declined = 'declined'
}


