/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Submerchant
 */
export interface Submerchant {
    /**
     * A unique 25-character alphanumeric merchant identifier.
     * @type {string}
     * @memberof Submerchant
     */
    'submerchant_id': string;
    /**
     * The amount with tax included, greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
     * @type {number}
     * @memberof Submerchant
     */
    'amount': number;
    /**
     * The platform fee amount, tax included, greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
     * @type {number}
     * @memberof Submerchant
     */
    'platform_fee': number;
}

