/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MerchantRole } from './merchant-role';

export interface SubmerchantListItem {
    /**
     * Unique identifier for this sub-merchant.
     */
    'id': string;
    /**
     * Whether this merchant is operating in live (production) mode.
     */
    'live': boolean;
    /**
     * Timestamp when this merchant was created.
     */
    'created_at': string;
    /**
     * Timestamp when this merchant record was last updated.
     */
    'updated_at': string;
    /**
     * Account identifier associated with this merchant.
     */
    'account_id': string;
    /**
     * Display name of the sub-merchant.
     */
    'name': string;
    'platform_role': MerchantRole;
    /**
     * Account application status of the merchant.
     */
    'status': SubmerchantListItemStatusEnum;
    /**
     * Whether payments are enabled for this merchant.
     */
    'payments_enabled': boolean;
    /**
     * Whether payouts are enabled for this merchant.
     */
    'payouts_enabled': boolean;
}

export enum SubmerchantListItemStatusEnum {
    Accepted = 'accepted',
    Declined = 'declined'
}


