/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubscriptionPaymentDetails
 */
export interface SubscriptionPaymentDetails {
    /**
     * Payment method type for this subscription.
     * @type {string}
     * @memberof SubscriptionPaymentDetails
     */
    'type': string;
    /**
     * Card expiry month.
     * @type {string}
     * @memberof SubscriptionPaymentDetails
     */
    'month': string;
    /**
     * Card expiry year.
     * @type {string}
     * @memberof SubscriptionPaymentDetails
     */
    'year': string;
    /**
     * Customer\'s email address.
     * @type {string}
     * @memberof SubscriptionPaymentDetails
     */
    'email': string;
}

