/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { Locale } from './locale';

/**
 * 
 * @export
 * @interface SubscriptionCustomer
 */
export interface SubscriptionCustomer {
    /**
     * Internal numeric ID of the customer.
     * @type {number}
     * @memberof SubscriptionCustomer
     */
    'id': number;
    /**
     * A unique 25-character alphanumeric resource identifier.
     * @type {string}
     * @memberof SubscriptionCustomer
     */
    'uuid': string;
    /**
     * Internal numeric ID of the merchant.
     * @type {number}
     * @memberof SubscriptionCustomer
     */
    'merchant_id': number;
    /**
     * Timestamp when the customer was created.
     * @type {string}
     * @memberof SubscriptionCustomer
     */
    'created_at': string;
    /**
     * Timestamp when the customer was last updated.
     * @type {string}
     * @memberof SubscriptionCustomer
     */
    'updated_at': string;
    /**
     * Customer\'s email address, or null if not provided.
     * @type {string}
     * @memberof SubscriptionCustomer
     */
    'email': string | null;
    /**
     * 
     * @type {Currency}
     * @memberof SubscriptionCustomer
     */
    'currency': Currency;
    /**
     * 
     * @type {Locale}
     * @memberof SubscriptionCustomer
     */
    'locale': Locale;
    /**
     * Customer-defined display name, or null if not set.
     * @type {string}
     * @memberof SubscriptionCustomer
     */
    'name': string | null;
    /**
     * Customer\'s phone number, or null if not set.
     * @type {string}
     * @memberof SubscriptionCustomer
     */
    'phone': string | null;
    /**
     * Timestamp when the customer was archived, or null if still active.
     * @type {string}
     * @memberof SubscriptionCustomer
     */
    'archived_at': string | null;
}



