/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TerminalErrorBody } from './terminal-error-body';

/**
 * 
 * @export
 * @interface TerminalError
 */
export interface TerminalError {
    /**
     * 
     * @type {TerminalErrorBody}
     * @memberof TerminalError
     */
    'error': TerminalErrorBody;
}

