/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TerminalErrorBody
 */
export interface TerminalErrorBody {
    /**
     * Machine-readable error code.
     * @type {string}
     * @memberof TerminalErrorBody
     */
    'code': string;
    /**
     * Human-readable error message.
     * @type {string}
     * @memberof TerminalErrorBody
     */
    'message': string;
    /**
     * The parameter that caused the error, if applicable.
     * @type {string}
     * @memberof TerminalErrorBody
     */
    'param': string;
    /**
     * Additional error details.
     * @type {object}
     * @memberof TerminalErrorBody
     */
    'details': object;
    /**
     * Detailed decline reason from the EMV terminal.
     * @type {string}
     * @memberof TerminalErrorBody
     */
    'decline_details': string;
}

