/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface TokenPaymentDetails {
    /**
     * Payment method type for this token (e.g. \"credit_card\").
     */
    'type': string;
    /**
     * Email address associated with this token.
     */
    'email'?: string;
    /**
     * Phone number associated with this token.
     */
    'phone'?: string;
    /**
     * Customer\'s given name.
     */
    'given_name'?: string;
    /**
     * Customer\'s family name.
     */
    'family_name'?: string;
    /**
     * Customer\'s given name in katakana.
     */
    'given_name_kana'?: string;
    /**
     * Customer\'s family name in katakana.
     */
    'family_name_kana'?: string;
    /**
     * Convenience store slug selected for this token (e.g. \"seven-eleven\").
     */
    'store'?: string;
}

