/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';

export interface Transfer {
    /**
     * The type identifier for this transfer record.
     */
    'type': string;
    /**
     * Identifier of the merchant receiving the funds.
     */
    'recipient': string;
    /**
     * Identifier of the merchant sending the funds.
     */
    'remitter': string;
    /**
     * Amount greater than or equal to 0, in the lowest denomination of the currency (e.g. cents for USD).
     */
    'amount': number;
    'currency': Currency;
    /**
     * Timestamp when the transfer occurred.
     */
    'happened_at': string;
}



