/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';

export interface UpdateMerchantRequestExpirySettingsInner {
    'slug'?: UpdateMerchantRequestExpirySettingsInnerSlugEnum;
    'currency'?: Currency;
    'expiry_days': number;
}

export enum UpdateMerchantRequestExpirySettingsInnerSlugEnum {
    BankTransfer = 'bank_transfer',
    Konbini = 'konbini'
}


