/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaymentDetailsAll } from './payment-details-all';

/**
 * 
 * @export
 * @interface UpdatePaymentRequest
 */
export interface UpdatePaymentRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdatePaymentRequest
     */
    'description'?: string;
    /**
     * 
     * @type {object}
     * @memberof UpdatePaymentRequest
     */
    'metadata'?: object;
    /**
     * 
     * @type {PaymentDetailsAll}
     * @memberof UpdatePaymentRequest
     */
    'payment_details'?: PaymentDetailsAll;
}

