/* tslint:disable */
/* eslint-disable */
/**
 * KOMOJU API
 * Full featured access to the KOMOJU payments system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Locale } from './locale';

/**
 * 
 * @export
 * @interface UpdatePaymentMethodRequest
 */
export interface UpdatePaymentMethodRequest {
    /**
     * 
     * @type {Locale}
     * @memberof UpdatePaymentMethodRequest
     */
    'locale'?: Locale;
    /**
     * Business opening time for this merchant\'s store.
     * @type {string}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.open_time'?: string;
    /**
     * Business closing time for this merchant\'s store.
     * @type {string}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.close_time'?: string;
    /**
     * URL to the merchant\'s privacy policy page.
     * @type {string}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.privacy_policy_url'?: string;
    /**
     * URL to the merchant\'s terms of service page.
     * @type {string}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.terms_of_service_url'?: string;
    /**
     * File IDs of uploaded PCI compliance proof documents.
     * @type {Array<string>}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.pci_compliance_proofs'?: Array<string>;
    /**
     * File IDs of uploaded shareholder register documents.
     * @type {Array<string>}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.shareholder_registers'?: Array<string>;
    /**
     * Whether the merchant has previously processed credit card payments.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.has_processed_cc_before'?: boolean;
    /**
     * Whether the merchant directly handles or stores card information.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.processes_card_info'?: boolean;
    /**
     * Whether the merchant conducts door-to-door sales.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.conducts_door_to_door_sales'?: boolean;
    /**
     * Whether the merchant conducts telemarketing activities.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.conducts_telemarketing'?: boolean;
    /**
     * Whether the merchant operates a multi-level marketing scheme.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.conducts_mlm_scheme'?: boolean;
    /**
     * Whether the merchant offers business opportunity schemes.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.conducts_business_opportunity_scheme'?: boolean;
    /**
     * Whether the merchant provides services subject to the Specified Commercial Transaction Act.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.provides_specified_continuous_services'?: boolean;
    /**
     * Whether the merchant has violated the Consumer Contract Act.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.violated_consumer_contract_act'?: boolean;
    /**
     * Whether the merchant has violated the Commercial Transaction Act.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'shared_payment_method_data.violated_commercial_transaction_act'?: boolean;
    /**
     * Whether the merchant has accepted LINE Pay\'s terms of service.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'linepay.accepted_line_tos'?: boolean;
    /**
     * Serialized form fields for the LINE Pay application.
     * @type {string}
     * @memberof UpdatePaymentMethodRequest
     */
    'linepay.fields'?: string;
    /**
     * Whether the merchant has accepted PayPay\'s terms of service.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'paypay.accepted_paypay_tos'?: boolean;
    /**
     * Serialized form fields for the PayPay application.
     * @type {string}
     * @memberof UpdatePaymentMethodRequest
     */
    'paypay.fields'?: string;
    /**
     * Whether the merchant has accepted Merpay\'s terms of service.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'merpay.accepted_merpay_tos'?: boolean;
    /**
     * Serialized form fields for the Merpay application.
     * @type {string}
     * @memberof UpdatePaymentMethodRequest
     */
    'merpay.fields'?: string;
    /**
     * Estimated monthly number of convenience store payments.
     * @type {number}
     * @memberof UpdatePaymentMethodRequest
     */
    'convenience_store.expected_number_of_payments'?: number;
    /**
     * Serialized form fields for the convenience store application.
     * @type {string}
     * @memberof UpdatePaymentMethodRequest
     */
    'convenience_store.fields'?: string;
    /**
     * Whether the merchant\'s website is publicly accessible.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.site_is_public'?: boolean;
    /**
     * Confirmation that products are not delivered directly from producers.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.no_direct_delivery_from_producer'?: boolean;
    /**
     * Confirmation that the merchant does not sell tickets.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.no_ticket_sales'?: boolean;
    /**
     * Confirmation that the order flow matches Seven-Eleven\'s requirements.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.correct_flow_for_order_items'?: boolean;
    /**
     * Confirmation that all ordered items will be delivered within two months.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.delivery_within_two_months'?: boolean;
    /**
     * Confirmation that all items are priced below the konbini payment limit.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.all_items_are_cheaper_than_konbini_limit'?: boolean;
    /**
     * Confirmation that any required sales permit numbers are displayed.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.display_sales_permit_number'?: boolean;
    /**
     * Confirmation that the order fee is clearly displayed to customers.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.order_fee_is_displayed'?: boolean;
    /**
     * Confirmation that transactions are domestic only.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.no_international_transaction'?: boolean;
    /**
     * Confirmation that site info matches the Specified Commercial Transaction Law disclosure page.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.provided_info_matches_sctl'?: boolean;
    /**
     * Confirmation that the SCTL page includes a phone number.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.sctl_page_has_phone_number'?: boolean;
    /**
     * Confirmation that product detail pages are publicly viewable.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.product_pages_are_public'?: boolean;
    /**
     * Confirmation that items have been sold at regular (non-discounted) price before.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.have_sold_as_regular_price'?: boolean;
    /**
     * Free-text notes for the Seven-Eleven application.
     * @type {string}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.note'?: string;
    /**
     * Serialized form fields for the Seven-Eleven application.
     * @type {string}
     * @memberof UpdatePaymentMethodRequest
     */
    'seven_eleven.fields'?: string;
    /**
     * Confirmation that the site has appropriate access restrictions in place.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'visa_mastercard_credit_card.access_restrictions'?: boolean;
    /**
     * Confirmation that multi-factor authentication is implemented.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'visa_mastercard_credit_card.mfa_implementation'?: boolean;
    /**
     * Confirmation that account lockout policies are in place.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'visa_mastercard_credit_card.account_lock'?: boolean;
    /**
     * Confirmation that public directory listing is disabled.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'visa_mastercard_credit_card.public_directories'?: boolean;
    /**
     * Confirmation that file extension restrictions are enforced.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'visa_mastercard_credit_card.file_extension_restrictions'?: boolean;
    /**
     * Confirmation that regular vulnerability assessments are conducted.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'visa_mastercard_credit_card.vulnerability_assessments'?: boolean;
    /**
     * Confirmation that the site is protected against SQL injection and XSS attacks.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'visa_mastercard_credit_card.sql_injection_and_xss'?: boolean;
    /**
     * Confirmation that source code security review is performed.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'visa_mastercard_credit_card.source_code_review'?: boolean;
    /**
     * Confirmation that anti-virus software is installed and maintained.
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'visa_mastercard_credit_card.anti_virus_software'?: boolean;
    /**
     * Serialized form fields for the Visa/Mastercard credit card application.
     * @type {string}
     * @memberof UpdatePaymentMethodRequest
     */
    'visa_mastercard_credit_card.fields'?: string;
    /**
     * Confirmation that the site has appropriate access restrictions in place (JCB/Amex/Diners).
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'jcb_amex_diners_credit_card.access_restrictions'?: boolean;
    /**
     * Confirmation that multi-factor authentication is implemented (JCB/Amex/Diners).
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'jcb_amex_diners_credit_card.mfa_implementation'?: boolean;
    /**
     * Confirmation that account lockout policies are in place (JCB/Amex/Diners).
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'jcb_amex_diners_credit_card.account_lock'?: boolean;
    /**
     * Confirmation that public directory listing is disabled (JCB/Amex/Diners).
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'jcb_amex_diners_credit_card.public_directories'?: boolean;
    /**
     * Confirmation that file extension restrictions are enforced (JCB/Amex/Diners).
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'jcb_amex_diners_credit_card.file_extension_restrictions'?: boolean;
    /**
     * Confirmation that regular vulnerability assessments are conducted (JCB/Amex/Diners).
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'jcb_amex_diners_credit_card.vulnerability_assessments'?: boolean;
    /**
     * Confirmation that the site is protected against SQL injection and XSS attacks (JCB/Amex/Diners).
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'jcb_amex_diners_credit_card.sql_injection_and_xss'?: boolean;
    /**
     * Confirmation that source code security review is performed (JCB/Amex/Diners).
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'jcb_amex_diners_credit_card.source_code_review'?: boolean;
    /**
     * Confirmation that anti-virus software is installed and maintained (JCB/Amex/Diners).
     * @type {boolean}
     * @memberof UpdatePaymentMethodRequest
     */
    'jcb_amex_diners_credit_card.anti_virus_software'?: boolean;
    /**
     * Serialized form fields for the JCB/Amex/Diners credit card application.
     * @type {string}
     * @memberof UpdatePaymentMethodRequest
     */
    'jcb_amex_diners_credit_card.fields'?: string;
}



